### ISSUE TITLE
Define an extensible pbstream file format

### ISSUE THREAD

**Issue by gaschler** [googlecartographer/cartographer#1009]
Currently,

- changes to the pbstream file format makes all older files unreadable
- the pbstream file format is only implicitly defined in `SaveState`.

We should provide a file format that changes very rarely. Also, reading older files should be supported if only optional messages have been added (for instance, reading files without landmarks should be supported).

**Comment by ojura** [comment]
Related: https://github.com/googlecartographer/rfcs/blob/master/text/0015-serialization-header.md

Haven't had the time to start looking into implementing this, though.

**Comment by gaschler** [comment]
Closing as fixed by #1174
