### ISSUE TITLE
PoseGraphInterface can mostly be const

### ISSUE THREAD

**Issue by gaschler** [googlecartographer/cartographer#1021]
Currently, all methods in `PoseGraphInterface` are not const, even though most of them can be.
I think the reason was that they require a read mutex, but semantically, they are const.

**Comment by SirVer** [comment]
That is a philosophical decision. We decided way back that in Cartographer, const should mean the same for the compiler and us, so we never used mutable ever. Mutable is also a slippery slope, diluting the possibility to correctly reason about class state from the outside. I think the Chromium project landed on the other side, using mutable all over the place and trying to express with `const` semantic constness.

Further reading, though a bit outdated:
- https://www.amazon.de/More-Effective-Addison-Wesley-Professional-Computing-ebook/dp/B004VSMDNY

**Comment by ojura** [comment]
I stumbled into this talk, which I found interesting:
https://channel9.msdn.com/posts/C-and-Beyond-2012-Herb-Sutter-You-dont-know-blank-and-blank

**Comment by sebastianklose** [comment]
@ojura - this is a nice talk, thanks for sharing.

For those who can't spare the time to watch it, the summary is that in C+11 the meaning of `const` and `mutable` has change away from "logically const" to "thread-safe" (bitwise const or internally synchronized). Meaning, declaring a synchronized object (like a mutex) `mutable` is concise and actually desired.

That being said, I will move forward with changing `Cartographer` classes to reflect this, as it also makes other classes using these object more sane in terms of `const`-ness.
