### ISSUE TITLE
Cartographer Bazel Build super slow in loop_closure

### ISSUE THREAD

**Issue by cschuet** [googlecartographer/cartographer#1037]
With the cartographer_grpc_server build by Bazel 2D SLAM is not real time anymore. Most probably Ceres is not correctly configured for the Bazel build.

**Comment by gaschler** [comment]
Maybe related to #971, perhaps Ceres is built without using `suitesparse`.

**Comment by cschuet** [comment]
Fixed by https://github.com/googlecartographer/cartographer/commit/2be3c1f6365c89cbe707bd89279f757129153c7c
