### ISSUE TITLE
Robot base drifts drastically away after sometime with warning of range_data_collator

### ISSUE THREAD

**Issue by hz658832** [googlecartographer/cartographer#1089]
Hey cartographer community, 

I got a terrible error that my robot base drifts quickly away from the right position, this problem can be seen in the following pic. I am just wondering what is wrong because this problem doesnot happen every time, if I relaunch the whole system, it could word as wished. I noticed this problem twice, last time I just reinstalled the OS (ubuntu 16) after updating, because the problem came out after updating the OS. After reinstalling, it works again. 
The problem happens with the warning of  range_data_collator.cc: Dropped 796 earlier points. And I guess, perhaps there is something wrong with the laser scanner data or other libs. 

Could someone help me or is someone suffering from the same problem?
I am so appreciate for the cartographer team.
![rviz_screenshot_2018_04_19-13_31_45](https://user-images.githubusercontent.com/18262391/38989453-41f675d4-43d7-11e8-9260-76c67a078113.png)

Thx.
Best regards

**Comment by gaschler** [comment]
Please follow the default issue template instructions, in particular please post the results of cartographer_rosbag_validate.

**Comment by hz658832** [comment]
Hey there,
I found out the problem, nothing to do with the algorithm, my computer doesnot work somehow.
thx.

**Comment by bigpigsu** [comment]
@hz658832 Hey,there,
I have the same problem with you, could you please help me or let me know what's wrong with it?
I am so appreciate for you
