### ISSUE TITLE
Odometry check failed

### ISSUE THREAD

**Issue by gullermo** [googlecartographer/cartographer#1110]
Hello, I recently managed to use cartographer for SLAM purposes, the problem is that the performance is definetly no accurate. I am using a rotating planar lidar to get a 3D infromation of the environment  (maybe this is why the liocalization is not accurate). The point is that I want to use the odometry form the wheels and other sensosrs to make the SLAM more robust. Thus I set the following parameters in the backpack 3D.lua:

options = {
  map_builder = MAP_BUILDER,
  trajectory_builder = TRAJECTORY_BUILDER,
  map_frame = "map",
  tracking_frame = "imu_link",
  published_frame = "odom",
  odom_frame = "odom",
  provide_odom_frame = false,
  publish_frame_projected_to_2d = false,
  use_odometry = true,
  use_nav_sat = false,
  use_landmarks = false,
  num_laser_scans = 1,
  num_multi_echo_laser_scans = 0,
  num_subdivisions_per_laser_scan = 1,
  num_point_clouds = 0,
  lookup_transform_timeout_sec = 0.2,
  submap_publish_period_sec = 0.3,
  pose_publish_period_sec = 5e-3,
  trajectory_publish_period_sec = 30e-3,
  rangefinder_sampling_ratio = 1.,
  odometry_sampling_ratio = 1.,
  fixed_frame_pose_sampling_ratio = 1.,
  imu_sampling_ratio = 1.,
  landmarks_sampling_ratio = 1.,
}

TRAJECTORY_BUILDER_3D.num_accumulated_range_data = 160

MAP_BUILDER.use_trajectory_builder_3d = true
MAP_BUILDER.num_background_threads = 7
POSE_GRAPH.optimization_problem.huber_scale = 5e2
POSE_GRAPH.optimize_every_n_nodes = 320
POSE_GRAPH.constraint_builder.sampling_ratio = 0.03
POSE_GRAPH.optimization_problem.ceres_solver_options.max_num_iterations = 10
POSE_GRAPH.constraint_builder.min_score = 0.62
POSE_GRAPH.constraint_builder.global_localization_min_score = 0.66

return options

I have a topic that is publishing a nav_msgs/Odometry msg in the odom topic as specified in the cartographer documentation. When I run the .launch file I get the following error:

[FATAL] [1524643855.448762349, 1524210165.508541094]: F0425 10:10:55.000000 16791 global_trajectory_builder.cc:96] Check failed: odometry_data.pose.IsValid() { t: [0.000000, -0.000000, 0.020000], q: [0.000000, 0.000000, 0.000000, 0.000000] }

Any idea to solve this problem would be appreciated
Thanks in advance!

**Comment by gaschler** [comment]
> global_trajectory_builder.cc:96] Check failed: odometry_data.pose.IsValid() { t: [0.000000, -0.000000, 0.020000], q: [0.000000, 0.000000, 0.000000, 0.000000] }

You are sending empty data, which includes an invalid quarternion.

BTW, how many planes does your lidar provide?
Have you successfully tuned without odometry?

If not, have you tried 2D first? It is much easier to start with.

**Comment by gullermo** [comment]
Thanks for the quick answer!
Without the odometry it does not crash, and it works, the problem is that the SLAM is not accurate at all that's why a wanted to insert /odom in the system.
Any idea why is it empty? My /odom topic is publishing messages...
It's a single plane laser rotating. Yo mean how many planes each rotation?
I tried 2D without odom, getting the same results than the ones i got using 3D.
Thanks again!

**Comment by gullermo** [comment]
BTW here is my /odom msg:
pose: 
  pose: 
    position: 
      x: 0.0
      y: 0.0
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.0
  covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
twist: 
  twist: 
    linear: 
      x: 0.195269629359
      y: 0.0
      z: 0.0
    angular: 
      x: 0.0
      y: 0.0
      z: -0.000553466903511
  covariance: [0.0004232949286233634, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0004232949286233634, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0002294552541570738]

**Comment by gullermo** [comment]
Ok, I can see that the pose field is completley empy. Is that the reason why cartographer crash?

**Comment by gaschler** [comment]
Yes. Cartographer dies on purpose when it sees an invalid quaternion.

**Comment by gullermo** [comment]
Ok. Thank you again, i will fix it and report the outcomes.

**Comment by gullermo** [comment]
I solved the odometry problem, but now im getting the following mistake:
FATAL] [1524651299.060136403, 1524210166.016200277]: F0425 12:14:59.000000 21138 map_by_time.h:43] Check failed: data.time > std::prev(trajectory.end())->first (636598069658837698 vs. 636598069658837698)

**Comment by gullermo** [comment]
OK,I managed to solve this issue by lowering the odometry_sampling_ratio. Now i can launch the cartographer without errors. Thanks! I close the issue and mark it as solved.

**Comment by gaschler** [comment]
> solve this issue by lowering the odometry_sampling_ratio

Just for documentation, you are only hiding the real issue that some of your input packets are invalid and dropping every nth packet. This is not fixed.

**Comment by gullermo** [comment]
Could it be because I am using a filtered bag file?

**Comment by gaschler** [comment]
Closing inactive issues.
