### ISSUE TITLE
Bug: trajectory builder options of empty trimmed trajectories are serialized

### ISSUE THREAD

**Issue by MichaelGrupp** [googlecartographer/cartographer#1111]
How to reproduce:

* run pure localization
* finish pure localization trajectory (should get trimmed, i.e. pose graph size of this trajectory == 0)
* serialize state

Let `X` be the number of frozen trajectories, `Y` the number of _active_ localization trajectories and `Z` the _total_ number of trajectories that have ever been active. All numbers at the time of serialization.

If we then load the state we get the error:

 > load state --> Check failed: pose_graph_proto.trajectory_size() == all_builder_options_proto.options_with_sensor_ids_size() (`X+Y` vs. `Z`)

This means that at least the options for an empty, finished trajectory were still lying around at serialization time.

**Comment by gaschler** [comment]
It seems like this check was removed by 73d18e5fc54bfa4e, is this still happening on current map?
If yes, this is of course a bug because you should be able to Save/Load.

**Comment by MichaelGrupp** [comment]
Didn't check that yet. Can you assign this issue to me so I have it in my list? Thanks

**Comment by sebastianklose** [comment]
@MichaelGrupp Hopefully #1214 should fix this. Can you give it another shot?

**Comment by MichaelGrupp** [comment]
Works, but the deletion breaks a check in cartographer_ros. Luckily I'm working on integrating the trajectory state there ;)

Here's the PR, it's published a bit earlier than planned now because of this bug but it's ready from my side.

**Comment by MichaelGrupp** [comment]
PR: https://github.com/googlecartographer/cartographer_ros/pull/910
