### ISSUE TITLE
kSubmapsToKeep config parameter for pure localization

### ISSUE THREAD

**Issue by AlexReimann** [googlecartographer/cartographer#1116]
A config parameter for how many submaps are kept during pure localization would be good.
Currently it is hard coded [here](https://github.com/googlecartographer/cartographer/blob/41f17e57cd6c3af382399db15507f70c5f7865fc/cartographer/mapping/map_builder.cc#L139) to `3`:

```c++
  if (trajectory_options.pure_localization()) {
    constexpr int kSubmapsToKeep = 3;
    pose_graph_->AddTrimmer(common::make_unique<PureLocalizationTrimmer>(
        trajectory_id, kSubmapsToKeep));
}
```

This can limit the pose optimization, especially if you run with a low `TRAJECTORY_BUILDER_3D.submaps.num_range_data`

**Comment by gaschler** [comment]
Sounds good, I can review a PR for this. The OverlappingSubmapTrimmer does use config values, you can use that as an example.
