### ISSUE TITLE
Initial pose feature does not work.

### ISSUE THREAD

**Issue by pifon2a** [googlecartographer/cartographer#1146]
Launching with `start_trajectory_with_default_topics = false`:
```
catkin_make_isolated --use-ninja 
source devel_isolated/setup.bash  
roslaunch cartographer_ros demo_backpack_2d_localization.launch \
  load_state_filename:=${SOME_PBSTREAM}
```
and then
```
./devel_isolated/cartographer_ros/lib/cartographer_ros/cartographer_start_trajectory \
 --configuration_directory="${CARTOROS}/cartographer_ros/configuration_files" \
 --configuration_basename="backpack_2d_localization.lua" \
 --initial_pose="{ to_trajectory_id=0, relative_pose={translation={1, 0, 0},rotation={0.0,0.0,0.0} }}" \
rosbag play --clock ${SOME_BAG}
```
does not work.

**Comment by MichaelGrupp** [comment]
What exactly doesn't work?

I can confirm that this works at least with an older version of cartographer_ros @ b4e7705159 - we are also using it on our robots.

**Comment by slamer-run** [comment]
@pifon2a @MichaelGrupp 
In the previous version of cartograoher_ros, it worked. However, at least this commit @ e4bfd557975443c3be71253adde71e153379a258, it showed ERROR message. Error message is related to below code.

`if (srv.response.status.code != cartographer_ros_msgs::StatusCode::OK) {
    LOG(ERROR) << "Error starting trajectory - message: '"
               << srv.response.status.message
               << "' (status code: " << std::to_string(srv.response.status.code)
               << ").";
    return false;
  } '

**Comment by MichaelGrupp** [comment]
That's code I added. But this doesn't produce any problems with the version I mentioned. I can take a look at this with the current HEAD the next days.

What's the exact error output?

**Comment by MichaelGrupp** [comment]
I could happily send initial poses with the current master. Still an issue for you?

**Comment by pifon2a** [comment]
Probably, I was doing something wrong. Closing it.
