### ISSUE TITLE
hello,Relatively poor registration accuracy at rest

### ISSUE THREAD

**Issue by xiangkui123** [googlecartographer/cartographer#1173]
hello I found several problems,Lead to poor trajectory accuracy.
1.Trajectory registration accuracy is poor at rest,Accuracy fluctuations of about 3-5cm in the same place.
2.Silver metal has a great impact on velodyne ranging
3.The overall track positioning accuracy is poor, about 10cm

**Comment by xiangkui123** [comment]
1.Velodyne noise points and outliers in this province,The main boundary point is relatively poor.
![top3](https://user-images.githubusercontent.com/9855744/40692697-df15ccf6-63e5-11e8-8fed-9a16030ad24e.png)

2.Silver Metal Effect on Velodyne Ranging
![default](https://user-images.githubusercontent.com/9855744/40692767-40f6f792-63e6-11e8-9d40-40f9a2823d18.png)

The actual construction of elevator doors affects the construction.


3.Trajectory registration accuracy is poor at rest,Accuracy fluctuations of about 3-5cm in the same place. 
![default](https://user-images.githubusercontent.com/9855744/40692869-cb69d660-63e6-11e8-8028-21e1b564db4b.png)

**Comment by xiangkui123** [comment]
The front-end registration itself is greatly influenced by Velodyne noise and outliers. Is there any improvement? The measured positioning accuracy in 3D is about 10cm, and the z-axis value is easy to float or fluctuate. We started to do a good initialization.

**Comment by xiangkui123** [comment]
![screenshot from 2018-04-01 17 47 14](https://user-images.githubusercontent.com/9855744/40692991-9c744272-63e7-11e8-848a-25fe3f19b024.png)

**Comment by xiangkui123** [comment]
Trajectory accuracy is measured by repeated positioning, registration accuracy observes the trajectory fluctuations through stationary equipment.Data analysis through CloudCompare.

**Comment by xiangkui123** [comment]
There is another problem I found that there is a serious stratification of the stairs up and down!
1.From the top view, the floors fluctuate so much
![2018-04-28-14-38-55 bag_xray_xz_all](https://user-images.githubusercontent.com/9855744/40693413-d416eff2-63e9-11e8-86a7-e197c1fa41d3.png)

![2018-04-28-14-38-55 bag_xray_xy_all](https://user-images.githubusercontent.com/9855744/40693406-cd1eee48-63e9-11e8-8003-d75eaabf6b73.png)

![2018-05-24-13-57-07 bag_xray_xy_all_color](https://user-images.githubusercontent.com/9855744/40693490-3a0f8f3a-63ea-11e8-9724-5168a26613a6.png)

![2018-05-24-13-57-07 bag_xray_xz_all](https://user-images.githubusercontent.com/9855744/40693499-416d03c0-63ea-11e8-9090-0399f818f676.png)

![2018-05-24-13-57-07 bag_xray_yz_all](https://user-images.githubusercontent.com/9855744/40693506-4912e7ac-63ea-11e8-801d-0fa5d764791f.png)

2.Up and down multi-level stairs,The side is a bit fluttering
![2018-05-24-14-11-28 bag_xray_xz_all](https://user-images.githubusercontent.com/9855744/40693517-56e47828-63ea-11e8-9ad3-6896a27ed2c7.png)
![2018-05-24-14-11-28 bag_xray_yz_all](https://user-images.githubusercontent.com/9855744/40693523-5c37fec6-63ea-11e8-92e4-87e8d53ca57f.png)

How to solve the problem of floor flutter?

**Comment by xiangkui123** [comment]
Sorry lost a silver metal effect on registration at rest,On the right is the recessed place where there are two elevator doors.
![slam](https://user-images.githubusercontent.com/9855744/40693841-33c70908-63ec-11e8-8627-f0e88337f27d.png)

**Comment by cschuet** [comment]
Thanks for your comments and the illustrations.

It is hard to make concrete suggestions without knowing more about your specific setup. If you feel comfortable with this, please fork the cartographer_ros repository and add your setup specific configuration files there and upload a representative sample rosbag.

It would be interesting to understand parameters such as grid resolution and how you do the accumulation of your velodyne data (I assume you accumulate a single revolution?). When you feel the input data from your laser is too noisy (because of silver metal) you can try to accumulate more than one revolution to achieve more averaging.

**Comment by gaschler** [comment]
Thanks for sharing your results, this is a very cool setup.

Without seeing any config or data (consider at least sharing cartographer_rosbag_validate output), I can only give some ideas

* The trajectories are not ideal for mapping. Walk more circular routes, not just back and forth. Walk up and down two different stairways. Global SLAM will then be better.
* Take the imu/laser transform that cartographer log outputs in the end to calibrate your urdf. This would fix a systematic tilt angle (moving downwards/upwards while walking through long corridor)

> The front-end registration itself is greatly influenced by Velodyne noise and outliers. Is there any improvement?

Tune the filters, especially the maximum ray length for insertions.

> 2.Silver metal has a great impact on velodyne ranging

To help here, I guess we would need to see example data.

**Comment by xiangkui123** [comment]
This is a set of data I collected，I need to count the number of trees and the perimeter, but I find that the trunk is very thick and I'm already thin.

![Uploading data_tree_other.png…]()

**Comment by xiangkui123** [comment]
![data_tree](https://user-images.githubusercontent.com/9855744/41073394-a3ccdba2-6a35-11e8-993e-92b25031b5ed.png)
![data_tree_other](https://user-images.githubusercontent.com/9855744/41073397-a98f89ea-6a35-11e8-9395-af4e01fa4115.png)

**Comment by xiangkui123** [comment]
![all_tree](https://user-images.githubusercontent.com/9855744/41075533-9be39eb2-6a3f-11e8-94d8-02a00c5dea9f.png)
