### ISSUE TITLE
Bug in map_by_time.h?

### ISSUE THREAD

**Issue by CycleMark** [googlecartographer/cartographer#1186]
Hi,

I'm launching cartographer with the command:

roslaunch cartographer_turtlebot turtlebot_urg_lidar_2d.launch configuration_basename:=turtlebot_urg_lidar_2d.lua 

It starts building a map without any issues. Then after a while I get the error below, and it crashes out. I've looked at the map_by_time.h file. Should the check the GE instead of GT?

Thanks

Mark

This is running with a RPLIDAR A2 with on an intel UP board (I've not seen any resource issues: CPU/Mem both fine) controlling a Kobuki base. 

Log trace:

[ INFO] [1528323196.350296204]: I0606 23:13:16.000000  7712 constraint_builder_2d.cc:266] Node (0, 3292) with 105 points on submap (0, 6) differs by translation 0.01 rotation 0.007 with score 70.2%.
F0606 23:13:16.394685  7654 map_by_time.h:43] Check failed: data.time > std::prev(trajectory.end())->first (636639199963165713 vs. 636639199963165713)
[FATAL] [1528323196.395379396]: F0606 23:13:16.000000  7654 map_by_time.h:43] Check failed: data.time > std::prev(trajectory.end())->first (636639199963165713 vs. 636639199963165713)
[ INFO] [1528323196.412679360]: I0606 23:13:16.000000  7714 constraint_builder_2d.cc:266] Node (0, 3293) with 102 points on submap (0, 28) differs by translation 0.00 rotation 0.007 with score 68.3%.
[ INFO] [1528323196.422098096]: I0606 23:13:16.000000  7715 constraint_builder_2d.cc:266] Node (0, 3294) with 105 points on submap (0, 6) differs by translation 0.01 rotation 0.002 with score 68.8%.
[ INFO] [1528323196.517653602]: I0606 23:13:16.000000  7712 constraint_builder_2d.cc:266] Node (0, 3295) with 101 points on submap (0, 28) differs by translation 0.01 rotation 0.006 with score 65.4%.
[ INFO] [1528323196.547375411]: I0606 23:13:16.000000  7713 constraint_builder_2d.cc:266] Node (0, 3296) with 105 points on submap (0, 6) differs by translation 0.01 rotation 0.004 with score 67.2%.
*** Check failure stack trace: ***
    @     0x7fe1cad7d5cd  google::LogMessage::Fail()
    @     0x7fe1cad7f433  google::LogMessage::SendToLog()
    @     0x7fe1cad7d15b  google::LogMessage::Flush()
    @     0x7fe1cad7fe1e google::LogMessageFatal::~LogMessageFatal()
    @           0x6e2c96 cartographer::mapping::optimization::OptimizationProblem2D::AddImuData()
    @           0x6fe59e cartographer::mapping::PoseGraph2D::AddImuData()
    @           0x68983d cartographer::sensor::Dispatchable<>::AddToTrajectoryBuilder()
    @           0x6882da cartographer::mapping::CollatedTrajectoryBuilder::HandleCollatedSensorData()
    @           0x688d0e _ZNSt17_Function_handlerIFvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt10unique_ptrIN12cartographer6sensor4DataESt14default_deleteISB_EEEZNS9_7mapping25CollatedTrajectoryBuilderC4EPNSA_17CollatorInterfaceEiRKSt3setINSG_26TrajectoryBuilderInterface8SensorIdESt4lessISM_ESaISM_EES8_ISL_SC_ISL_EEEUlS7_SE_E_E9_M_invokeERKSt9_Any_dataS7_OSE_
    @           0x667cea _ZNSt17_Function_handlerIFvSt10unique_ptrIN12cartographer6sensor4DataESt14default_deleteIS3_EEEZNS2_8Collator13AddTrajectoryEiRKSt13unordered_setINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4hashISF_ESt8equal_toISF_ESaISF_EERKSt8functionIFvRKSF_S6_EEEUlS6_E_E9_M_invokeERKSt9_Any_dataOS6_
    @           0x66cab4 cartographer::sensor::OrderedMultiQueue::Dispatch()
    @           0x66d988 cartographer::sensor::OrderedMultiQueue::Add()
    @           0x6680c0 cartographer::sensor::Collator::AddSensorData()
    @           0x68712d cartographer::mapping::CollatedTrajectoryBuilder::AddData()
    @           0x689f1e cartographer::mapping::CollatedTrajectoryBuilder::AddSensorData()
    @           0x5cb0cd cartographer_ros::SensorBridge::HandleRangefinder()
    @           0x5cc321 cartographer_ros::SensorBridge::HandleLaserScan()
    @           0x5cc5b7 cartographer_ros::SensorBridge::HandleLaserScanMessage()
    @           0x59ee29 cartographer_ros::Node::HandleLaserScanMessage()
    @           0x5b174e boost::detail::function::void_function_obj_invoker1<>::invoke()
    @           0x5bf599 ros::SubscriptionCallbackHelperT<>::call()
    @     0x7fe1c86d5e2d  ros::SubscriptionQueue::call()
    @     0x7fe1c867b6f8  ros::CallbackQueue::callOneCB()
    @     0x7fe1c867d0fb  ros::CallbackQueue::callAvailable()
    @     0x7fe1c86d9ef9  ros::SingleThreadedSpinner::spin()
    @     0x7fe1c86beedb  ros::spin()
    @           0x596e34  cartographer_ros::(anonymous namespace)::Run()
    @           0x593e64  main
    @     0x7fe1c70ca830  __libc_start_main
    @           0x596959  _start
    @              (nil)  (unknown)
[cartographer_node-2] process has died [pid 7654, exit code -6, cmd /home/mark/catkin_ws/install_isolated/lib/cartographer_ros/cartographer_node -configuration_directory /home/mark/catkin_ws/install_isolated/share/cartographer_turtlebot/configuration_files -configuration_basename turtlebot_urg_lidar_2d.lua points2:=/camera/depth/points __name:=cartographer_node __log:=/home/mark/.ros/log/90601b34-69d5-11e8-bde8-74da38733b6f/cartographer_node-2.log].
log file: /home/mark/.ros/log/90601b34-69d5-11e8-bde8-74da38733b6f/cartographer_node-2*.log
^C[cartographer_occupancy_grid_node-4] killing on exit
[flat_world_imu_node-3] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
mark@kobukiMxnet2:~$

**Comment by gaschler** [comment]
map_by_time checks that trajectory (here: IMU) data are strictly monotonous in time and dies if that is not the case.
You have the same timestamp twice, which is an input data issue.
(Usually, our approach is that cartographer is pretty strict about input data, and cartographer_ros is allowed to clean things up and warn to some extent.)
Please post the result of rosbag_validate on your input data.

**Comment by YuehChuan** [comment]
yes it's sensor delivery out of order.
Check my issue on turtlebo3
https://hackmd.io/s/r1fAEBGlX#
https://github.com/ROBOTIS-GIT/turtlebot3/issues/217

Howerver, although with the check flat_node emu to keep the sequence. It still by accident.
https://github.com/googlecartographer/cartographer_turtlebot/blob/master/cartographer_turtlebot/cartographer_turtlebot/flat_world_imu_node_main.cc#L41

**Comment by CycleMark** [comment]
Hi,

As requested I've posted the result of rosbag_validate and the connection graphs.

Thanks

Mark

[cartographer_bagfile_validate.txt](https://github.com/googlecartographer/cartographer/files/2081907/cartographer_bagfile_validate.txt)
![screenshot from 2018-06-07 20-52-27](https://user-images.githubusercontent.com/27418725/41123149-9e38fe4a-6a95-11e8-8621-1fabe121cd7b.png)

**Comment by gaschler** [comment]
Thanks for posting the validation results.

> W0607 20:54:25.473460  6217 rosbag_validate_main.cc:103] frame_id gyro_link time 1528400647360684776: IMU linear acceleration is 0 m/s^2, expected is [3, 30] m/s^2. (It should include gravity and be given in m/s^2.) linear_acceleration 0 0 0
> E0607 20:54:25.473747  6217 rosbag_validate_main.cc:315] Sensor with frame_id "gyro_link" jumps backwards in time. Make sure that the bag contains the data for each frame_id sorted by header.stamp, i.e. the order in which they were acquired from the sensor.

Your IMU input is erroneous, both its timestamps and measurements.

Since you use the 2D pipeline, you can just disable the use of IMU by setting

```
TRAJECTORY_BUILDER_2D.use_imu_data = false
```

**Comment by gaschler** [comment]
Closing as answered/inactive
