### ISSUE TITLE
Compiling cartographer & cartographer_ros with a customer install directory for protobuf3

### ISSUE THREAD

**Issue by jochemverboom** [googlecartographer/cartographer#1197]
I am trying to build/install cartographer and cartographer_ros with a custom location for protobuf3 while not adding the protobuf3 to the install folder. I do not want to add protobuf3 to my current catkin workspace directory as I have different packages depended on the system installation of protobuf2 (If i add protobuf3 to the install directory all works fine, but I need to use a custom location).

I have forked cartographer (see: [fork](https://github.com/jochemverboom/cartographer)). With this fork and the changes to the cmakelist I am able to compile cartographer but no longer able to compile cartographer_ros due to conflicting version of protobuf. See error:

```
 error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
```

I feel like I am missing something in the cmakelist of cartographer.

**Comment by gaschler** [comment]
Protobuf has a compiler and a library, all have to match in both cartographer and cartographer_ros builds.

I think you can select which protobuf to use in the cmake flags
```
 Protobuf_INCLUDE_DIR             /usr/local/include                                                              
 Protobuf_LIBRARY_DEBUG           /usr/local/lib/libprotobuf.so                                                   
 Protobuf_LIBRARY_RELEASE         /usr/local/lib/libprotobuf.so                                                   
 Protobuf_LITE_LIBRARY_DEBUG      /usr/local/lib/libprotobuf-lite.so                                              
 Protobuf_LITE_LIBRARY_RELEASE    /usr/local/lib/libprotobuf-lite.so                                              
 Protobuf_PROTOC_EXECUTABLE       /usr/local/bin/protoc                                                           
 Protobuf_PROTOC_LIBRARY_DEBUG    /usr/local/lib/libprotoc.so                                                     
 Protobuf_PROTOC_LIBRARY_RELEAS   /usr/local/lib/libprotoc.so   
```

Of course, you would install protobuf3 in a non-system folder, not in /usr/local.

Perhaps your solution is almost working, just look at the (hidden) cmake flags for both cartographer and cartographer_ros.

Yet another alternative solution is the install script here: https://github.com/googlecartographer/cartographer_ros/issues/625#issuecomment-358318701

**Comment by gaschler** [comment]
Closing as answered
