### ISSUE TITLE
Open House timezone inconsistency

### ISSUE THREAD

**Issue by FlorentRevest** [googlecartographer/cartographer#1211]
Hi. I just noticed that all of the slides you uploaded say that the next Open House meeting happens at "5pm CET" while the README says "5pm CEST". It looks like I missed today's Open House for this reason... It would be cool to fix this inconsistency, at least for the next slides! :)

**Comment by FlorentRevest** [comment]
Yeah, I agree that this CET/CEST difference is quite a pain. :) 
Thanks a lot!

**Comment by cschuet** [comment]
@pifon2a @gaschler So we don't forget :)
