### ISSUE TITLE
Deletable trajectories + landmarks seem broken

### ISSUE THREAD

**Issue by ojura** [googlecartographer/cartographer#1219]
Hi (@cschuet?), using landmarks seems to clash with the new `CanAddWorkItemModifying` stuff:

```
cartographer\cartographer\mapping\internal\3d\pose_graph_3d.cc:751] trajectory_id:0 has not been added but modification is requested.
```

With a stack trace like this:

```
    @   00007FF6DE1CC233  private: bool __cdecl cartographer::mapping::PoseGraph3D::CanAddWorkItemModifying(int) __ptr64
    @   00007FF6DE1CA7A5  public: virtual void __cdecl cartographer::mapping::PoseGraph3D::AddLandmarkData(int,struct cartographer::sensor::LandmarkData const & __ptr64) __ptr64
    @   00007FF6DE0811FA  public: void __cdecl cartographer_ros::SensorBridge::HandleLandmarkMessage....
```

Of course, could be that I messed something up, I will look into it as well :-)

**Comment by ojura** [comment]
I have also noticed that I get a bunch of these for the IMU as well (even if I disable landmarks).

**Comment by gaschler** [comment]
So you are getting these as warnings, because nobody has called `AddTrajectoryIfNeeded` yet.
If it goes away after the first node is added, this is harmless.
If it happens later, it would be good to find out the reason.

**Comment by ojura** [comment]
Okay, the real bug is that my landmarks queue is blocking everything for some reason. Not sure why that has started happening since I pulled master, will investigate. Thanks.

**Comment by ojura** [comment]
Just to follow up, #1184 was causing problems for me. My sensor data was marked as `SensorId::SensorType::FIXED_FRAME_POSE` (because that's what I'm using landmarks for)  instead of `SensorId::SensorType::LANDMARK`, so the multi ordered sensor queue thought it needed to collate this as well.
