### ISSUE TITLE
Trouble:run cartograhy with hokuyo UTM-30LX 

### ISSUE THREAD

**Issue by Tednsn** [googlecartographer/cartographer#1232]
HI ，everyone，when i run cartograhy with hokuyo UTM-30LX only,i met a bug as follwing. So far,i have connected laser properly .when i run the lauch,the erros came out,and the rviz showed the Fixed Frame in golbe statues was wrong, and Fixed Frame  in globe options was map not  laser. Can anyone give me a idea about it ,thanks .

[FATAL] [1530619780.903185079]: F0703 20:09:40.000000  6158 lua_parameter_dictionary.cc:83] Check failed: status == 0 (2 vs. 0) [string "-- Copyright 2016 The Cartographer Authors..."]:43: attempt to index global 'SPARSE_POSE_GRAPH' (a nil value)

**Comment by gaschler** [comment]
SPARSE_POSE_GRAPH was renamed into POSE_GRAPH half a year ago. Please make sure you are running the latest version.
