### ISSUE TITLE
How can I run another bag file by cartographer demo

### ISSUE THREAD

**Issue by Jin-S-Kim** [googlecartographer/cartographer#1282]
Hello, I run cartographer demo in this link 

> https://google-cartographer-ros.readthedocs.io/en/latest/

I download this bag file

> https://storage.googleapis.com/cartographer-public-data/bags/backpack_2d/cartographer_paper_deutsches_museum.bag

I success `roslaunch cartographer_ros demo_backpack_2d.launch` for downloaded file.
And I want to run other bag file. 
cartographer_paper_deutsches_museum.bag file's topic and message Type are 
sensor_msg/Imu, sensor_msgs/MultiEchoLaserScan, sensor_msgs/MultiEchoLaserScan,
imu, vertical_laser_2d.

And I want to run bag file that has topic and message Type are
sensor_msgs/LaserScan, tf2_msgs/TFMessage, /scan, /tf.
I can't run this bag file by cartographer demo?
This is bag file link
https://drive.google.com/open?id=1RvyIg2J7Eh3u-10ppv1XEFjulKuWSL_h

**Comment by gaschler** [comment]
closing as answered
