### ISSUE TITLE
Map layering

### ISSUE THREAD

**Issue by Rmargin** [googlecartographer/cartographer#1299]
hi
Map stratification is easy to occur when the backpack is moving at high speed.What caused it?
I don't have access to GPS.
![view_image_right_test](https://user-images.githubusercontent.com/9855744/42915858-dede0368-8b34-11e8-938b-c3545982494c.png)
![screenshot from 2018-07-19 09 22 08](https://user-images.githubusercontent.com/9855744/42915957-55315024-8b35-11e8-993d-b5af3d18a9b7.png)
![screenshot from 2018-07-19 09 22 26](https://user-images.githubusercontent.com/9855744/42915959-5618b8c4-8b35-11e8-972b-2b585fedddca.png)

**Comment by Rmargin** [comment]
Our test environment is mainly highway, and the speed of movement is about 15km/h. When the speed is faster, the map layer is more obvious.
In the low-speed test process map layering, you can properly circle or wait in the same place, the stratification phenomenon will close, but the high-speed situation does not improve the effect

**Comment by Rmargin** [comment]
![Uploading time_2_image.png…]()
![Uploading end_time_point.png…]()
![Uploading end_time_point_test.png…]()
![Uploading Screenshot from 2018-07-25 18:07:37.png…]()

**Comment by Rmargin** [comment]
![init_time_image](https://user-images.githubusercontent.com/9855744/43194894-1c54242e-9036-11e8-927b-76e7617fbe0e.png)
![time_2_image](https://user-images.githubusercontent.com/9855744/43194900-21604a74-9036-11e8-9412-3f1a35023c83.png)
![end_time_point](https://user-images.githubusercontent.com/9855744/43194907-258d042a-9036-11e8-8544-6df754f94d39.png)
![end_time_point_test](https://user-images.githubusercontent.com/9855744/43194913-28f7633a-9036-11e8-8eb9-eb2b6abc9a15.png)
![screenshot from 2018-07-25 18 07 37](https://user-images.githubusercontent.com/9855744/43194921-2c68cd6a-9036-11e8-85db-f5ab00bcd01b.png)

**Comment by Rmargin** [comment]
hi
The trajectory is not closed properly,The speed of the backpack is about 30km/h.The journey is about 2-3km,How to solve this problem?tks.haha

**Comment by Rmargin** [comment]
@gaschler

**Comment by FlorentRevest** [comment]
If you want people to be helpful:

1. Follow [the issue template](https://github.com/googlecartographer/cartographer_ros/issues/new?labels=question) by uploading your ``.bag`` file and ``cartographer_ros`` fork.
2. Edit your comment instead of posting multiple comments in a row
3. Ask a **clear** question. "how to solve this" is not a clear question. Tons of screenshots is not a question either.
4. Don't highlight developers, they already get notifications. If they want to answer, they will, whenever their time will permit.

**Comment by Rmargin** [comment]
ok! haha
