### ISSUE TITLE
running on windows?

### ISSUE THREAD

**Issue by antithing** [googlecartographer/cartographer#134]
Has anyone got this up on windows? Is it possible?

Thanks!

**Comment by SirVer** [comment]
Nobody has! You could be the first....

That said, it probably requires quite some work.

**Comment by antithing** [comment]
the FIRST you say!  Sadly, i do not think my code-fu is up to it!

**Comment by SirVer** [comment]
Well, with ROS not running on Windows - Linux is kinda the lingua franca in robotics. Sorry.

Closing, as windows support is not on the roadmap for now.

**Comment by liuxinren456852** [comment]
I have successfully compiled in the windows platform！

**Comment by antithing** [comment]
Impressed! :) Any chance that you could share/github the code?

**Comment by tpengti** [comment]
I have successfully compiled in the windows platform for 2D-SLAM
https://github.com/tpengti/cartographer_windows

**Comment by sunmk2006** [comment]
I have successfully compiled in the windows platform for 2D-SLAM as @tpengti ,https://github.com/tpengti/cartographer_windows,The test routine will run for more than ten minutes , but in the linux platform this routine only takes three or four seconds to run,I couldn't understand the result because the windows Library's compilation did not change any code,Can someone help me?

**Comment by damonkohler** [comment]
@sunmk2006, it sounds like you compiled in debug mode or so.

**Comment by sunmk2006** [comment]
@damienrg ,yes,you are right,I compiled in release mode,The cartographer worked very well! Thank you very much!

**Comment by paul-michalik** [comment]
Did anybody considered merging the required changes back to master? Or were no changes required?

**Comment by mmazat** [comment]
Made it easy for everyone, cartographer is now compiled and build on windows by the Microsoft Vcpkg,  https://github.com/Microsoft/vcpkg

**Comment by antithing** [comment]
Thanks! Is this just the 2d slam, as in above posts? Or the 3d also?

**Comment by mmazat** [comment]
it is cartographer library in full...

**Comment by antithing** [comment]
Awesome! Thank you very much. I am trying to build this, with vcpkg, and it is failing with:

```
Error: Building package boost-config:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-config:x86-windows
  Vcpkg version: 0.0.104-unknownhash
```

What am I missing?

**Comment by mmazat** [comment]
This is boost installation problem. There might be hick ups but vcpkg works, in case of issue you may report them.. my advice is to use higher version of Visual Studio (2015 or 2017 perhaps)

**Comment by antithing** [comment]
I am on vs2017. I actually already have boost installed, can I just point the vcpkg to my existing files?

**Comment by ras0219-msft** [comment]
We use cmake, which uses curl internally, so you'll need to set the usual curl environment variables for your proxy (`HTTPS_PROXY`)[1].

[1] https://stackoverflow.com/questions/9445489/performing-http-requests-with-curl-using-proxy

**Comment by antithing** [comment]
Ah it was my firewall at the office. Another machine has it installing now. Thanks again! One more question... Is there any example / demo floating around to show how to use cartographer on windows, without ROS? If you could point me in the right direction to get started, it would be much appreciated.

**Comment by anitaHey** [comment]
@antithing I also look for the direction to get started with using cartographer on windows, without ROS. Is there any experience can share? Thank you so much!
