### ISSUE TITLE
LIDAR rays that don't hit anything don't seem to be taken into account for misses

### ISSUE THREAD

**Issue by RemiFabre** [googlecartographer/cartographer#1354]
Hi,

My understanding of this issue is that if the LIDAR ray doesn't hit anything because the nearest object is too far, then it's not used to compute misses (i.e. lowering the score of the squares that the ray went through in the occupancy grid). The symptom of this is that maps obtained through Cartographer are filled with greyish areas where they should be white, specifically on the path of the robot (cf picture).
![image](https://user-images.githubusercontent.com/9042540/43410029-d47d920e-9425-11e8-8d15-0df8513d4950.png)

Yet one of Cartographer parameters is the max distance of the LIDAR, so the expected behaviour would have been to compute misses up to that distance. Or am I missing something?

The only explanation for this behaviour that I can see is that some LIDARs can't tell the difference between very close and very far, hence "no distance measured"=>"let's not change the occupancy grid" seems a safe choice. But on our robot (a Turtlebot3), the LIDAR is centered and the size of the robot is large enough so that there can't (shouldn't) be objects too close, so the information "no distance measured" actually means "there are no objects closer to the max detection distance".

Is there a way to achieve this through configuration?

Thanks,

**Comment by gaschler** [comment]
> one of Cartographer parameters is the max distance of the LIDAR, so the expected behaviour would have been to compute misses up to that distance


Yes, TRAJECTORY_BUILDER_2/3D.max_range and TRAJECTORY_BUILDER_2/3D.missing_data_ray_length support what you are describing.
A miss is a distance measurement in the input scan larger than `max_range`.

(You can also tune the confidence at which misses are inserted, but usually there is no need to change this.
TRAJECTORY_BUILDER_2D.submaps.range_data_inserter.probability_grid_range_data_inserter.miss_probability = 0.49)

**Comment by RemiFabre** [comment]
Thank you for the fast answer. The configuration used for the map in the post is the following:

MAP_BUILDER.use_trajectory_builder_2d = true
TRAJECTORY_BUILDER_2D.min_range = 0.3
TRAJECTORY_BUILDER_2D.max_range = 3.5
TRAJECTORY_BUILDER_2D.missing_data_ray_length = 3.
TRAJECTORY_BUILDER_2D.use_imu_data = false
TRAJECTORY_BUILDER_2D.use_online_correlative_scan_matching = true
TRAJECTORY_BUILDER_2D.motion_filter.max_angle_radians = math.rad(15)POSE_GRAPH.constraint_builder.min_score = 0.55
POSE_GRAPH.constraint_builder.global_localization_min_score = 8.5
POSE_GRAPH.constraint_builder.fast_correlative_scan_matcher.linear_search_window = 3
POSE_GRAPH.constraint_builder.fast_correlative_scan_matcher.angular_search_window = math.rad(60.)
POSE_GRAPH.constraint_builder.fast_correlative_scan_matcher.branch_and_bound_depth = 10

My understanding is that if a distance greater than max_range is detected, then misses are recorded on a distance of missing_data_ray_length. Yet it doesn't seem to be working (as seen on the map, the robot path is trailed by a dark grey area).

Note: taking extreme values for these parameters does seem to work (max_range=1, missing_data_ray_length=2) but are unusable. An explanation would be that rays that are too far are treated by the LIDAR driver in a way that is not understood by cartographer (I think it writes a very high value, like 10000 m). We'll look into it and post an update.

**Comment by RemiFabre** [comment]
This is now solved, the issue was robot/driver dependent, the missing ray feature was working well on the Cartographer side.

If it helps someone with a turtlebot3:
Turns out it was the driver that was sending a distance of 0 (with intensity 0) when no measurement was made. We changed the driver (on the robot) so a measurement of [distance==0m, intensity==0] is changed to [distance==9m, intensity==0]. Also, it seems mandatory to change (on the driver) the attribute "range_max" of the scan message to a higher value (we set it to 10m).

We believe the intensity field is not used in Cartographer but haven't confirmed yet.

**Comment by ojura** [comment]
I remember running into this exact same thing with Sick LMS 100. Free range measurements were reported as zero-range measurements.

Since this appears to be a widespread behaviour, perhaps it could justify an „interpret zero as free range“ option in cartographer_ros?

**Comment by RemiFabre** [comment]
Does Sick have an intensity value ?

**Comment by ojura** [comment]
It does. These were zero as well.

**Comment by RemiFabre** [comment]
Ok then if it's a common convention then maybe the default behavior should be [distance==0 and intensity==0] => apply missing ray ?

**Comment by ojura** [comment]
Yeah, that's what I was suggesting. Maybe just distance==0 - just that measurement by itself does not make sense otherwise.

**Comment by Vineet-Pandey** [comment]
Was this incorporated in the later releases?
