### ISSUE TITLE
Cartographer for Quadcopter Pose Estimation

### ISSUE THREAD

**Issue by AmineElhafsi** [googlecartographer/cartographer#1358]
Would Cartographer be suitable to use for aerial vehicle localization/pose estimation in indoor, gps-denied settings? 

Thanks!

**Comment by FlorentRevest** [comment]
You can find great insights on the usage of Cartographer for drones in this issue: https://github.com/googlecartographer/cartographer_ros/issues/624
As far as I know, the pose extrapolator still works the same and would cause the same difficulties. You might consider changing the pose extrapolator or reverting to a previous version of Cartographer.
The lack of GPS really shouldn't be a problem though.

**Comment by AmineElhafsi** [comment]
Ah, that's helpful. Thank you!
