### ISSUE TITLE
Start point to the repository 

### ISSUE THREAD

**Issue by deidaraho** [googlecartographer/cartographer#1371]
Hello, 
I am interested in the loop closure algorithm introduced in your paper, "Real-time loop closure in 2D LIDAR SLAM" and want to learn more about how it is implemented. But after building this repository, I did not find any examples. 
Could I ask where in this code is a good start point for beginners? Thanks so much in advance!

Bests,
R.H

**Comment by cschuet** [comment]
Take a look at our documentation hosted [here](https://google-cartographer.readthedocs.io/en/latest/). I contains instructions how to download and run example rosbags and also some information that should make it easier for you to connect what you have read in the paper to code in the repository.

Feel free to reopen if you have further questions.
