### ISSUE TITLE
Save pose-graph

### ISSUE THREAD

**Issue by woshidaye** [googlecartographer/cartographer#1401]
Cartographer is SLAM based on graph optimization. I want to save the pose graph after the map is created. That is to say, the nodes (submaps' position), edges, constraints, and submaps corresponding to each node of the pose graph are saved. How can this be achieved?

**Comment by kdaun** [comment]
You can use the [`\write_state` service](https://google-cartographer-ros.readthedocs.io/en/latest/ros_api.html) to serialize the current state. See the [Assets write documentation](https://google-cartographer-ros.readthedocs.io/en/latest/assets_writer.html)  for an example.

**Comment by gaschler** [comment]
Closing as answered
