### ISSUE TITLE
Allow snapshotting of large pose graphs from cartographer server

### ISSUE THREAD

**Issue by cschuet** [googlecartographer/cartographer#1422]
Currently when snapshotting the cartographer server state using MapBuilderService::WriteState, we stream back a sequence of SerializedData protos. One of them contains the PoseGraphProto which can easily grow beyoned the maximum supported protobuf message size of gRPC (currently 10 MB).

I would be better to add a WriteStateToFile() gRPC method which allows the client to ask the server to directly write the pbstream to a local file.

This method should also be invoked from the cartographer_grpc_node when the ROS service for saving state is called.

**Comment by cschuet** [comment]
@MichaelGrupp FYI

**Comment by MichaelGrupp** [comment]
Resolved, you can close this.

**Comment by cschuet** [comment]
Resolved by https://github.com/googlecartographer/cartographer/pull/1424.
