### ISSUE TITLE
install cartographer error

### ISSUE THREAD

**Issue by wxt-github** [googlecartographer/cartographer#1433]
when I install cartographer:
libcommon_lua_parameter_dictionary.a(lua_parameter_dictionary.cc.o)：在函数‘cartographer::common::LuaParameterDictionary::Partial(std::string const&, std::string const&, std::unique_ptr<cartographer::common::FileResolver, std::default_delete<cartographer::common::FileResolver> >, std::function<void (lua_State*)>)’中：
lua_parameter_dictionary.cc:(.text+0x1926)：对‘lua_rotate’未定义的引用
collect2: error: ld returned 1 exit status
make[2]: *** [cartographer/common/common_lua_parameter_dictionary_test] 错误 1
make[1]: *** [cartographer/common/CMakeFiles/common_lua_parameter_dictionary_test.dir/all] 错误 2
make[1]: *** ....
Please help me!

**Comment by gaschler** [comment]
closing as inactive
