### ISSUE TITLE
Can we have a 3D map?

### ISSUE THREAD

**Issue by pangchenglin** [googlecartographer/cartographer#1447]
Cartographer can give us a 2D grid occupying map .But in outdoor navigation，we want use a 3D map
to ahcieve robot navigation.So ,how can we base on the method of scan to map to achieve 3d map to navigation.？

**Comment by gaschler** [comment]
To output a 3D point cloud of the entire pose graph, use https://google-cartographer-ros.readthedocs.io/en/latest/assets_writer.html#assets-writer
with the additional processing step:
```
    {
      action = "write_ply",
      filename = "points.ply",
    },
```

**Comment by gaschler** [comment]
Closing as answered
