### ISSUE TITLE
GPU Acceleration

### ISSUE THREAD

**Issue by apache8080** [googlecartographer/cartographer#1461]
In this paper on [cartographer](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/45466.pdf) it mentions this: "The  operator  is  presented  with  an  up-
to-date  preview  of  the  final  map  as  a  GPU-accelerated
combination  of  finished  submaps  and  the  current  submap.".

I was wondering if google cartographer by default had GPU accelerated features by default or are there settings that allow for GPU acceleration.

**Comment by gaschler** [comment]
The current version uses only the CPU with vector arithmetic.
