### ISSUE TITLE
Add landmarks to existing map for pure localization mode

### ISSUE THREAD

**Issue by johuber** [googlecartographer/cartographer#1470]
In our application we have a known (mapped) environment and operate in pure localization mode.
Since we have poor localization performance in certain parts of the map and possibly also to accelerate initialization, we'd like to add distinct landmarks (QR-Tags or similar) at certain places.

Is there a way to define the landmark poses with respect to the map at this stage? We already have a pbstream of the map, but don't want to rebuild the map because it takes too much time considering that we will need to try different landmark configurations.

**Comment by gaschler** [comment]
The current API does not allow editing existing pbstreams.
You could write this feature by adding backdated landmark observations but this would only be a hack.

**Comment by johuber** [comment]
Ok, I thought so.

I also experimenting with running mapping mode again on the same map, but loading an existing .pbstream to start. In general this seems to work and the map is updated, but somehow the newly observed landmarks are not introduced to the pose graph, or at least the marker array for landmarks remains empty. 

What's the reason for this? Shouldn't they be added?

**Comment by johuber** [comment]
I just found the answer to my question.

As @ojura stated in his [comment](https://github.com/googlecartographer/cartographer/pull/988#issuecomment-373159268) in PR #988 , I would now be interested in the case, where I can add landmarks on top of a frozen trajectory.

I will submit a PR for this. My proposal:
- always allow introduction of new landmarks
- set parameter blocks of a trajectory's landmarks constant whenever `freezeTrajectory` is called for it.

Any objections?
