### ISSUE TITLE
Ways to manually remove lidar measurments

### ISSUE THREAD

**Issue by AlexReimann** [googlecartographer/cartographer#1480]
I want to start filtering certain semi-static obstacles, e.g. parked cars, from the offline map creation.
The approach would be to simply drop all measurements hitting the cars out of the input point cloud of cartographer.

Could cartographer handle these missing range measurement (inconsistent number of points per measurement), or should I rather set them to `NAN`?

**Comment by gaschler** [comment]
You can filter points in the data structures that have timestamps for each point.
(Filtering LaserScan messages would give wrong timestamps of following points in that message.)
Setting "NAN/not a number" is not supported.

**Comment by AlexReimann** [comment]
Thanks
