### ISSUE TITLE
different formulation regarding to transformation between two poses

### ISSUE THREAD

**Issue by PeterTdd** [googlecartographer/cartographer#1499]
In your cartographer documentation, the Relative Transform is given below:
<img width="725" alt="transformation" src="https://user-images.githubusercontent.com/19349900/51068262-abfd1800-1656-11e9-821b-c7d5c47af852.png">

However, in the "ComputeUnscaledError" function in cost_helpers_impl.h, you forgot to add the transpose to the rotation matrix R(theta): which is shown below:
<img width="527" alt="computeunscalederror" src="https://user-images.githubusercontent.com/19349900/51068286-fbdbdf00-1656-11e9-8e7c-77bdbd066dcf.png">

Do I misunderstand the formulation ?

**Comment by sebastianklose** [comment]
No you don't. But the rotation matrix is defined by
```
cos(theta), -sin(theta)
sin(theta), cos(theta)
```

Thus `h[3]` in the code implements the transpose.
