### ISSUE TITLE
Spare RTK GPS FIX positions

### ISSUE THREAD

**Issue by athtest800** [googlecartographer/cartographer#1512]
Hello!
Is it possible to calibrate the map while building it by using spare RTK GPS positions?
Can the GPS be used for indoor SLAM, by going outside the building and getting FIX position, then go again inside and using regular SLAM algorithm, over and over again in order to make global position map?
So, the RTK FIX GPS position will not be available all the time, there will be 5-10 minutes interval when it is possible to go outside and get position.
Thank you.

**Comment by chriswsuarez** [comment]
Did you ever come to an answer on this?  I'm looking to do the same thing but am running into issues just getting cartographer to even accept the GPS fix data.
