### ISSUE TITLE
NormalEstimation Test Flaky

### ISSUE THREAD

**Issue by kdaun** [googlecartographer/cartographer#1530]
https://github.com/googlecartographer/cartographer/pull/1508#issuecomment-470083540 indicates that the normal estimation tests are flaky.
Test log: https://travis-ci.org/googlecartographer/cartographer/jobs/502507460

**Comment by pifon2a** [comment]
I will take a look.

**Comment by kdaun** [comment]
It's the same issue as in https://github.com/googlecartographer/cartographer/pull/1520.
There are instances of RangeData that need to be initialized explicitly in
https://github.com/googlecartographer/cartographer/blob/master/cartographer/mapping/internal/2d/normal_estimation_2d_test.cc
We have to replace
`sensor::RangeData range_data;` by   `auto range_data = sensor::RangeData();`.

**Comment by pifon2a** [comment]
solved by https://github.com/googlecartographer/cartographer/pull/1532
