### ISSUE TITLE
Question: 3D scan matching vs ICP

### ISSUE THREAD

**Issue by kings-landing** [googlecartographer/cartographer#1539]
What is 3D scan matching algorithm? Is it similar to the 2D scan matching algorithm described in the paper? For 3D scan matching, is it better compared to point-to-normal ICP for two frame case? Thanks!

**Comment by gaschler** [comment]
Please take a look at
https://github.com/googlecartographer/cartographer/blob/master/cartographer/mapping/internal/constraints/constraint_builder_3d.cc#L231

In 3D, we first run the "Fast correlative scan matcher".
It takes uses the tilt angle from IMU, and then search in 4 DoF in a certain range of parameters (position and z-orientation). It matches a filtered laser scan (a set of hundreds of points) against a submap/`HybridGrid`, which is a 3D occupancy grid.
After that, we run a "Ceres scan matcher", which does full 6D matching by non-linear optimization, again from scan to submap/occupancy grid.

So, there is no ICP or point-to-normal. Also, there is no frame-to-frame matching.

**Comment by kings-landing** [comment]
Thanks!
