### ISSUE TITLE
Question: What IMU and additional hardware was used to record the 3d backpack datasets?

### ISSUE THREAD

**Issue by DuowenQian** [googlecartographer/cartographer#1568]
For the 3d backpack dataset recorded in the Deutsches Museum, what IMU was used? Also, what exactly is in the backpack apart from the IMU and Velodyne LIDARs? Was there additional hardware was used to timesync with the LIDAR data and if so, what was done exactly? I'm trying to build a similar backpack setup. Thanks!

**Comment by pifon2a** [comment]
@DuowenQian I believe it cannot be disclosed.
