### ISSUE TITLE
Calibration using evaluation - using cartographer autogenerate ground truth for automatic calibration tool

### ISSUE THREAD

**Issue by shirbarzel** [googlecartographer/cartographer#1588]
I would like to create a system for automatic calibration of the lua parameters using the above tool:
The method will be as follows:
* First creating a ground truth pbstream by using optimization and view by eye that a good map created (optimize_every_n_nodes = 60)
* Running on the same bag but change the parameters (optimize_every_n_node = 0)
* Run cartographer_compute_relations_metrics between ground truth and the created pbstream
* Get the minimum as possible for the sum of : (Abs translational error + Sqr translational error + Abs rotational error + Sqr rotational error).

1. Does this way make sense?

2. How would you recommend creating the best ground truth? 
* For example today for creating ground truth I put parameters in the lua file that consume a lot of resources(high CPU) - include "optimize every_n_node" 

3. As I understood this tool can only help calibrating the trajectory builder parameters(is it true?) 
Which parameters would you recommend calibrate using this automatic tool?

Thanks in advance,
Shir

**Comment by Sumyer** [comment]
Hello,
I have the same goal as yours.
Would you like to reopen this question and continue communicating?
