### ISSUE TITLE
Question: simultaneous start of cartographer

### ISSUE THREAD

**Issue by tama0701** [googlecartographer/cartographer#1645]
Can cartographer start on multiple machines on the same network at the same time?

I want to update the map created on the first machine on the second machine.
However, since I have just started studying ROS recently, I cannot come up with a solution.

I'm not good at English.
please forgive me.

**Comment by shamengjun** [comment]
This is not the cartographer's  problem, you can configrure your ros system master-slave mode, master machine run cartographer building map node, slave machine receive map.
