### ISSUE TITLE
Issue restarting trajectory using pbstream and mutable_initial_trajectory_pose

### ISSUE THREAD

**Issue by glucas350** [googlecartographer/cartographer#1674]
I am attempting to reinitialize cartographer mapping using a saved .pbstream file and setting a new starting position for the robot.  The trajectory builder does not seem to initialize fully when using the InitialTrajectoryPose option.  Below is the pertinent snippet of code for initialization, I am not using the ROS implementation.

```
TrajectoryBuilderOptions trajectoryOptions;
::cartographer::transform::Rigid3d::AngleAxis rotation(heading,
          ::cartographer::transform::Rigid3d::Vector(0.0, 0.0, 1.0));
        ::cartographer::transform::Rigid3d::Vector initPose
          = ::cartographer::transform::Rigid3d::Vector(
            x * cInches2Meters,
            y * cInches2Meters, 0);
        cartographer::transform::Rigid3d relativePose
          = ::cartographer::transform::Rigid3d(initPose, rotation);

::cartographer::mapping::proto::InitialTrajectoryPose pose;
pose.set_to_trajectory_id(0);
        // Must use normalized quaternion for rotation
        // cartographer::transform::Rigid3d relativePose
        //  = cartographer::transform::Rigid3d(position, rotation.normalized());
        *pose.mutable_relative_pose() = cartographer::transform::ToProto(
          relativePose);
        pose.set_timestamp(0);
        *trajectoryOptions.mutable_initial_trajectory_pose() = pose;

// Add a new trajectory
AddTrajectory(trajectoryOptions);
```

Here are 3 images describing what I am seeing.   The blue circle represents the position of the robot and the red is showing the 2D lidar scan.

This is position  x:0, y:0, heading:0 in the map. 
<img width="726" alt="Screen Shot 2020-02-26 at 3 57 19 PM" src="https://user-images.githubusercontent.com/9246364/75389760-1867c480-58b5-11ea-93ac-0d384ace0b6e.png">

This is where I am attempting to set the position to using the above code snippet.
<img width="752" alt="Screen Shot 2020-02-26 at 4 01 45 PM" src="https://user-images.githubusercontent.com/9246364/75389785-24538680-58b5-11ea-85ee-6381afb73074.png">

This is the result.  The robot position seems to be correct, but the range data is not in the correct location.
<img width="743" alt="Screen Shot 2020-02-26 at 4 02 17 PM" src="https://user-images.githubusercontent.com/9246364/75389795-29b0d100-58b5-11ea-9ee2-5f4bae91a9e0.png">

I am getting the robot position using the LocalSlamResultCallback()
```
<const LocalTrajectoryData::LocalSlamData>trajectory_data;

// Robot Position
::cartographer::transform::Rigid3d position = pose * trajectory_data->local_pose;
  x = position.translation().x();
  y = position.translation().y();
  h = ::cartographer::transform::GetYaw(position.rotation());

// Range Data
coords.resize(trajectory_data->range_data_in_local.returns.size()*2);
  unsigned int idx = 0;
  for (const ::cartographer::sensor::RangefinderPoint &point :
    trajectory_data->range_data_in_local.returns) {
    coords[idx]   = point.position(0);
    coords[idx+1] = point.position(1);
    idx += 2;
  }
```

Is there something else I should be doing to have the LocalSlamResultCallback() RangeData position correctly reflect the initial trajectory position?

**Comment by shreyasgokhale** [comment]
Hi @glucas350 , I am facing a similar issue. If you don't mind, can you please share how did you solve this?

**Comment by glucas350** [comment]
I realized that I wasn't transforming the range_data_in_local into the global frame.  

`
::cartographer::transform::Rigid3d globalTransform
    = mapBuilder->pose_graph()->GetLocalToGlobalTransform(trajectoryId);
`
