### ISSUE TITLE
Error cartographer ROS

### ISSUE THREAD

**Issue by alexx100-cmd** [googlecartographer/cartographer#1678]
I new in ROS and i tried to prove the slam method cartographer with turtlebot3 (MELODIC) and i have a problem with the map, i did not make anything code all is the demo for the installation
![image](https://user-images.githubusercontent.com/62269358/76810837-15c20600-67b5-11ea-8889-69f41dc4b99c.png)

The console show me this:
Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.1 timeout was 0.1.
I can see the robot and the laser scan but not generated a map. Can i help me??

**Comment by mdenizturkmen** [comment]
Do you have robot_state_publisher node running? 

`<node pkg="robot_state_publisher" type="robot_state_publisher" name="robot_state_publisher" output="screen">
      <param name="publish_frequency" type="double" value="50.0" />
  </node>`
