### ISSUE TITLE
Cartographer expects the IMU to point Z-wards

### ISSUE THREAD

**Issue by ojura** [googlecartographer/cartographer#194]
This report is a continuation of [this thread](https://groups.google.com/forum/#!topic/google-cartographer/QiesM3P39ao) on the Cartographer Google group. I think @SirVer is right, that Cartographer simply expects that the IMU is mounted with the `z` axis pointing upwards. The warning is caused by the following check in `cartographer/mapping_2d/local_trajectory_builder.cc`, which calculates the inclination of the IMU tracker orientation estimate from the `z` axis and complains if > 20:

```
  // Log a warning if the backpack inclination exceeds 20 degrees. In these
  // cases, it's very likely that 2D SLAM will fail.
  const Eigen::Vector3d gravity_direction =
      imu_tracker_->orientation() * Eigen::Vector3d::UnitZ();
  const double inclination = std::acos(gravity_direction.z());
```

If this assumption is not fulfilled (in our example, the IMU is mounted with the `y` axis pointing up), this inclination amounts to approximately 90 degrees and causes these seemingly harmless warnings about the maximum inclination being exceeded. Other than that, Cartographer seems to work fine. 

I am not sure if I can definitely propose how to solve this. Perhaps this check can be rethought - e.g. transform the IMU tracker orientation estimate into the laser sensor frame, which by standard conventions should definitely have its `z` axis pointing up; then apply the check above in the same way.

If you would like to have a look for yourself, I have prepared an [example bag](http://larics.fer.hr/owncloud/index.php/s/RP2CCbCWUb396Xo) which matches the situation described in the Google groups thread. To run, go into the `launch` folder and execute `roslaunch t20_cartographer.launch` from there.

**Comment by SirVer** [comment]
I think we can just remove this check. It is a leftover from a different use case internally. @damonkohler Agreed?

**Comment by damonkohler** [comment]
+1
