### ISSUE TITLE
request ROS Indigo binary release

### ISSUE THREAD

**Issue by jack-oquin** [googlecartographer/cartographer#204]
We are interested in running this package on multiple robots of the [UTexas Building-Wide Intelligence project](https://github.com/utexas-bwi). It would be very helpful to have a ROS Indigo release for cartographer which we could depend on.

If you are not familiar with the process of creating ROS binary releases, the [bloom package](http://wiki.ros.org/bloom) works great. After some [initial setup](http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease), the job is quick and easy. 

I am willing to assist by answering questions, as are the other members of the [ROS discourse release category](https://discourse.ros.org/c/release). 

I believe other ROS users would also benefit from having a binary release available.

cc: @jsinapov, @Ashay-Lokhande

**Comment by SirVer** [comment]
Cartographer team can't support maintaining a build for binary releases at this point in time. We would of course love to see such a thing happen though.

Paging @tfoote, can OSRF maybe help out here?

**Comment by jihoonl** [comment]
ping @jspricke FYI

**Comment by jack-oquin** [comment]
If you are willing to [make source releases](http://wiki.ros.org/bloom/Tutorials/PrepareUpstream), where appropriate, we would be willing to handle the ROS binary distribution steps.

**Comment by damonkohler** [comment]
Thanks, Jack. That looks like a pretty low bar and I'm happy to take it on. I'll be out all next week, but I can look into it once I'm back.

**Comment by damonkohler** [comment]
Ok, @jack-oquin. I think we're all set for you to do the first binary release!

**Comment by jack-oquin** [comment]
OK, sorry for slow response, I've gotten way behind on e-mail lately and still catching up.

**Comment by jack-oquin** [comment]
Is there also interest in a Kinetic release?

**Comment by damonkohler** [comment]
@jack-oquin Yes, I think so. We currently have CI configured for Indigo and Kinetic. We've had requests for Lunar, but aren't yet testing it.
