### ISSUE TITLE
velodyne frequency

### ISSUE THREAD

**Issue by sunmk2006** [googlecartographer/cartographer#206]
The frequency of the topic of vertical_laser_3d or horizontal_laser_3d in your ros bag data is about 1527HZ,but the frequency of the velodyne 16 is 10HZ,Why?How do you split the data of the laser scans from the velodyne's lidar?Excuse me for my bad english!

**Comment by damonkohler** [comment]
We generate a point cloud for every UDP packet from the Velodyne. Chopping it up this way is both convenient and allows Cartographer to unwarp a full revolution. At 10 Hz, there's generally quite a bit of distortion in the point cloud due to the motion of the sensor.
