### ISSUE TITLE
3d model

### ISSUE THREAD

**Issue by sunmk2006** [googlecartographer/cartographer#207]
if the cartograper can save a 3d point cloud model of the scanning room , how do it?

**Comment by damonkohler** [comment]
The primary output of Cartographer is a trajectory. From the trajectory, you can use the collected sensor data to generate a point cloud.

[cartographer_ros/assets_writer_main](https://github.com/googlecartographer/cartographer_ros/blob/master/cartographer_ros/cartographer_ros/assets_writer_main.cc) can be used to construct point clouds from the results of the [/finish_trajectory service](https://google-cartographer-ros.readthedocs.io/en/latest/ros_api.html#services). You can view the generated points clouds using the [point_cloud_viewer](https://github.com/googlecartographer/point_cloud_viewer).
