### ISSUE TITLE
when can call finish_trajectory service?

### ISSUE THREAD

**Issue by sunmk2006** [googlecartographer/cartographer#210]
when i call the service of finish_trajectory,it often return error:ERROR: transport error completing service call: unable to receive data from sender, check sender's logs for details,but What time is the right time？

**Comment by SirVer** [comment]
You can call this at any point in time when the system is SLAMing. Your errors are likely network errors unrelated to Cartographer.

**Comment by sunmk2006** [comment]
I used the old version of the program，It is now ready for use.
