### ISSUE TITLE
 Can I use a Velodyne VLP-16 lidar for 3D reconstruction？

### ISSUE THREAD

**Issue by sunmk2006** [googlecartographer/cartographer#213]
3D mapping you have tow lidars,a horizontal_laser_3d can do it too,but a vertical_laser_3d always failed, Can I use a tilted laser to mapping,(eg. A Velodyne VLP-16 lidar with a tilt of 45 degrees)to get trajectory and reconstruction?

**Comment by SirVer** [comment]
Theoretically yes, but practically the opening angle of the VLP16 is pretty small. This means that you see little of the world in one revolution and rarely enough to constrain the point cloud in all dimensions. If your environment is feature rich though, it might just work.

**Comment by yxting1994628** [comment]
Hello!Can you run cartographer with VLP16?

**Comment by damonkohler** [comment]
Yes, but you'll need 2 and an IMU for it to work out of the box.
