### ISSUE TITLE
how to build point cloud viewer?

### ISSUE THREAD

**Issue by sunmk2006** [googlecartographer/cartographer#217]
When I did the third step :“npm install", there was an error: npm WARN point_viewer@0.1.0 No repository field.

**Comment by SirVer** [comment]
Did you work it out?

**Comment by sunmk2006** [comment]
build successfully, but：
viki@viki:~/soft/point_cloud_viewer-master/target/release$ ls
build  build_octree  deps  examples  libpoint_viewer.rlib  native  viewer
viki@viki:~/soft/point_cloud_viewer-master/target/release$ build_octree
build_octree: command not found
viki@viki:~/soft/point_cloud_viewer-master/target/release$

**Comment by sunmk2006** [comment]
./build_octree generates a lot of files,but
./viewer /home/viki/source/data/cartographer_data/mode
Listening on port 5433.
IT seems to do nothing, No changes in memory and CPU ，What happened？

**Comment by SirVer** [comment]
open your browser to `http://localhost:5433`, then left click and drag a bit. It should load your points. use WASD to fly around, mouse wheel to adjust speed.

**Comment by sunmk2006** [comment]
You are right!!!
