### ISSUE TITLE
Does cartographer not support the laser scan data with frame_id [0] == '/'????

### ISSUE THREAD

**Issue by differkhun** [googlecartographer/cartographer#221]
Does cartographer not support the laser scan data with frame_id [0] == '/'????
I input a scan topic named /sickldmrs/scan0,and its frame_id is /ldmrs
And I got this problem

> 

 [FATAL] [1489632539.831538484, 1489560966.553811869]: F0316 10:48:59.000000 18821 sensor_data.cc:34] Check failed: frame_id[0] != '/' ('/' vs. '/') 

so how to fix it?  
thx a lot

**Comment by damonkohler** [comment]
That's correct and is the ROS way since [tf2](http://wiki.ros.org/tf2). You'll need to configure the node producing the sensor data to not include the leading slash.
