### ISSUE TITLE
Tools for integration testing

### ISSUE THREAD

**Issue by macmason** [googlecartographer/cartographer#239]
(This might end up in `cartographer_ros`.)

We need tools for doing integration testing: given some data, confirming that Cartographer's behavior doesn't change over time.

This is intended as a tracking issue for work TRI's planning to do on this.

@damonkohler @SirVer @wohe once upon a time, there was code for doing trajectory comparisons. Could that be made available?

@yutakaoka for TRI.

**Comment by wohe** [comment]
I just fixed #310. The idea is to use this generated ground truth data as input to `compute_relations_metric_main`, i.e.
1. Extract the computation of errors into a separate file.
2. Add support for reading a `GroundTruth` proto in addition to a text file with unix timestamps.
3. Use it for an integration test.

**Comment by SirVer** [comment]
@cschuet Is this done with the nighly pipeline running?

**Comment by cschuet** [comment]
With the inclusion of ground_truth data in the nightly pipeline I call this done.
