### ISSUE TITLE
Refactor multi-trajectory support to keep data separate for each trajectory

### ISSUE THREAD

**Issue by wohe** [googlecartographer/cartographer#256]
Currently many parts of the code, e.g. `SparsePoseGraph::GetTrajectoryNodes()`, use a vector that contains nodes from all trajectories interleaved. Each node knows its trajectory. `SparsePoseGraph::Constraint` contains a scan index into this flat list of nodes.

What should be done: Instead, nodes should be kept per trajectory. Constraints would then identify a node as a pair of trajectory ID (an integer 0, 1, ...) and a scan index (the index of the scan in its trajectory).

Similarly for submaps: Change the submap index in `SparsePoseGraph::Constraint` to a pair of trajectory ID and submap index inside this trajectory.

**Comment by SirVer** [comment]
I started looking into this - this will be pretty epic...
