### ISSUE TITLE
ZR300 + Cartograhper ROS 3D-mapping, IMU problem

### ISSUE THREAD

**Issue by operationflash** [googlecartographer/cartographer#305]
I'm currently using only a zr300 realsense camera and Cartographer ros.
I'm running the following launch files: zr300_nodelet_rgdb.launch (which can be found[ here](https://github.com/intel-ros/realsense/tree/indigo-devel/realsense_camera/launch)) and a launch file containing the following code:
![screenshot from 2017-05-23 14-10-04](https://cloud.githubusercontent.com/assets/6248649/26353620/97b6d420-3fc1-11e7-9fc8-13806ac336c0.png)

The configuration lua file contains the following code:
![screenshot from 2017-05-23 14-11-12](https://cloud.githubusercontent.com/assets/6248649/26353646/b296d09c-3fc1-11e7-81b3-bb7d9294f4f0.png)

In terminal I get the following output (and error meessage):
![cartographer_ros error 3d](https://cloud.githubusercontent.com/assets/6248649/26353369/692aaaf6-3fc0-11e7-8c21-bf0ada097490.png)
Unfortunately the error log file doesn't seem to exist.

Does anyone now a solution?

**Comment by Entropy512** [comment]
My first guess would be a problem with the timestamps of your IMU data?  As in they should be constantly increasing, but one message had a timestamp earlier than the previous one?

**Comment by operationflash** [comment]
@Entropy512 If I look at the IMU data, the time stamps seem to be increasing and in order.

**Comment by SirVer** [comment]
@operationflash No, they are not. Cartographer complains about that (see in your last screenshot, there is a CHECK line in the middle in red). When investigating, make sure you look at the `header.stamp` data, not at the timestamp when rosbag wrote this into its file.

**Comment by DriftingTimmy** [comment]
Have you succeeded in running your data in cartographer? Could you please show me your bagfile so I can figure out what I need to create my own bagfile.
@operationflash

**Comment by operationflash** [comment]
@DriftingTimmy the problem was solved, @SirVer was right. The IMU very rarely gave wrong timestamps which made it harder to find. This was solved bij using the flat_world_imu_node_main code found in cartographer_turtlebot and modifying it to only filter out bad data.
