### ISSUE TITLE
2D LIDAR manufacturer and type

### ISSUE THREAD

**Issue by tyuownu** [googlecartographer/cartographer#328]
we already know that the captured 3D bag data using Velodyne VLP-16 LIDAR, what sensor did it used to capture the 2D bag file?

**Comment by SirVer** [comment]
We used two [UTM-30LX-EW](https://www.hokuyo-aut.jp/search/single.php?serial=170). Where did you search for this information? Mind sending a PR to add this to where you searched for it?
