### ISSUE TITLE
pass-by-value on Eigen types may cause alignment issues

### ISSUE THREAD

**Issue by catskul** [googlecartographer/cartographer#35]
Per Eigen docs, passing eign types by value may cause alignment issues and unexplained crashes:

http://eigen.tuxfamily.org/dox-devel/group__TopicPassingByValue.html

At least two instance of this exist in the project.

`./cartographer/transform/transform.h`

```
template <typename T>
Eigen::Matrix<T, 3, 1> RotationQuaternionToAngleAxisVector( Eigen::Quaternion<T> quaternion) 
```
 and 
```
template <typename T>
Eigen::Quaternion<T> AngleAxisVectorToRotationQuaternion(Eigen::Matrix<T, 3, 1> angle_axis)

```

There may be others.

**Comment by SirVer** [comment]
Suggested fix is to pass by reference and copy internally. None of these are performance critical.
