### ISSUE TITLE
6/22 hangout slides

### ISSUE THREAD

**Issue by YuehChuan** [googlecartographer/cartographer#356]
Is 6/22 yesterday slides available now? TQ!
And for the ROS kinetic version, 
https://www.youtube.com/watch?v=GO_Du32Em9o
seems turtlebot3 already could run on it. I'll check.

**Comment by SirVer** [comment]
Slides are here: https://storage.googleapis.com/cartographer-public-data/cartographer-open-house/170622/sildes.pdf

Yes, Cartographer runs on the turtlebot. Why did you doubt that? Tuning for the depth camera is harder as for the lasers though.

**Comment by YuehChuan** [comment]
TQ!
