### ISSUE TITLE
Also use low resolution hybrid grids for finding loop closure constraints in 3D

### ISSUE THREAD

**Issue by damonkohler** [googlecartographer/cartographer#369]
Currently, loop closure constraints are found using the high resolution hybrid grid and then refined using the Ceres scan matcher, which uses both high and low resolution grids.

We may be able to improve performance by first searching for loop closures in the low resolutions grids and then continuing with the high resolution grid search in case of success.

**Comment by wohe** [comment]
Performance improvements were not implemented, but the low resolution grids are now taken into account during loop closure in 3D.
