### ISSUE TITLE
Build fails after recent changes

### ISSUE THREAD

**Issue by apr8** [googlecartographer/cartographer#397]
Hi,
I was able to build cartographer before the recent commit. But I recently pulled the changes to try out localization but I am getting errors when I build these package. I have shown the error below. What might be going wrong?
[42/237] cd /home/vecna/googlecartographer/cartographer/build && bash -c "find /hom... | sed 's/^/#/' > /home/vecna/googlecartographer/cartographer/build/AllFiles.cmake"
Files /home/vecna/googlecartographer/cartographer/build/AllFiles.cmake and - differ
[44/237] Building documentation.
Making output directory...
Running Sphinx v1.2.2
loading pickled environment... not yet created
building [html]: targets for 2 source files that are out of date
updating environment: 2 added, 0 changed, 0 removed
reading sources... [ 50%] configuration
reading sources... [100%] index

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 50%] configuration
writing output... [100%] index

writing additional files... genindex search
copying static files... WARNING: html_static_path entry u'/home/vecna/googlecartographer/cartographer/docs/source/_static' does not exist
done
copying extra files... done
dumping search index... done
dumping object inventory... done
build succeeded, 1 warning.
[47/237] Building CXX object CMakeFiles/cartographer.dir/cartographer/sensor/imu_data.cc.o
FAILED: /usr/bin/c++    -O3 -DNDEBUG -isystem /usr/local/include/eigen3 -isystem /home/vecna/catkin_ws_cartographer/install_isolated/include -isystem /usr/local/include -isystem /usr/include/cairo -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/freetype2 -isystem /usr/include/libpng12 -I. -I.. -isystem /usr/src/gmock/gtest/include     -pthread -std=c++11  -Wall -Wpedantic -Werror=format-security -Werror=missing-braces -Werror=reorder -Werror=return-type -Werror=switch -Werror=uninitialized -O3 -DNDEBUG -MMD -MT CMakeFiles/cartographer.dir/cartographer/sensor/imu_data.cc.o -MF "CMakeFiles/cartographer.dir/cartographer/sensor/imu_data.cc.o.d" -o CMakeFiles/cartographer.dir/cartographer/sensor/imu_data.cc.o -c ../cartographer/sensor/imu_data.cc
In file included from ../cartographer/sensor/imu_data.cc:17:0:
../cartographer/sensor/imu_data.h:34:1: error: ‘ImuData’ in namespace ‘cartographer::sensor::proto’ does not name a type
 proto::ImuData ToProto(const ImuData& imu_data);
 ^
../cartographer/sensor/imu_data.h:37:25: error: ‘ImuData’ in namespace ‘cartographer::sensor::proto’ does not name a type
 ImuData FromProto(const proto::ImuData& proto);
                         ^
../cartographer/sensor/imu_data.h:37:41: error: ISO C++ forbids declaration of ‘proto’ with no type [-fpermissive]
 ImuData FromProto(const proto::ImuData& proto);
                                         ^
../cartographer/sensor/imu_data.cc:24:1: error: ‘ImuData’ in namespace ‘cartographer::sensor::proto’ does not name a type
 proto::ImuData ToProto(const ImuData& imu_data) {
 ^
../cartographer/sensor/imu_data.cc:34:25: error: ‘ImuData’ in namespace ‘cartographer::sensor::proto’ does not name a type
 ImuData FromProto(const proto::ImuData& proto) {
                         ^
../cartographer/sensor/imu_data.cc:34:41: error: ISO C++ forbids declaration of ‘proto’ with no type [-fpermissive]
 ImuData FromProto(const proto::ImuData& proto) {
                                         ^
../cartographer/sensor/imu_data.cc: In function ‘cartographer::sensor::ImuData cartographer::sensor::FromProto(const int&)’:
../cartographer/sensor/imu_data.cc:35:46: error: request for member ‘timestamp’ in ‘proto’, which is of non-class type ‘const int’
   return ImuData{common::FromUniversal(proto.timestamp()),
                                              ^
../cartographer/sensor/imu_data.cc:36:43: error: request for member ‘linear_acceleration’ in ‘proto’, which is of non-class type ‘const int’
                  transform::ToEigen(proto.linear_acceleration()),
                                           ^
../cartographer/sensor/imu_data.cc:37:43: error: request for member ‘angular_velocity’ in ‘proto’, which is of non-class type ‘const int’
                  transform::ToEigen(proto.angular_velocity())};
                                           ^
../cartographer/sensor/imu_data.cc:38:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1plus: some warnings being treated as errors
[47/237] Building CXX object CMakeFiles/cartographer.dir/cartographer/sensor/collator.cc.o
FAILED: /usr/bin/c++    -O3 -DNDEBUG -isystem /usr/local/include/eigen3 -isystem /home/vecna/catkin_ws_cartographer/install_isolated/include -isystem /usr/local/include -isystem /usr/include/cairo -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/freetype2 -isystem /usr/include/libpng12 -I. -I.. -isystem /usr/src/gmock/gtest/include     -pthread -std=c++11  -Wall -Wpedantic -Werror=format-security -Werror=missing-braces -Werror=reorder -Werror=return-type -Werror=switch -Werror=uninitialized -O3 -DNDEBUG -MMD -MT CMakeFiles/cartographer.dir/cartographer/sensor/collator.cc.o -MF "CMakeFiles/cartographer.dir/cartographer/sensor/collator.cc.o.d" -o CMakeFiles/cartographer.dir/cartographer/sensor/collator.cc.o -c ../cartographer/sensor/collator.cc
In file included from ../cartographer/sensor/data.h:22:0,
                 from ../cartographer/sensor/collator.h:26,
                 from ../cartographer/sensor/collator.cc:17:
../cartographer/sensor/range_data.h:52:1: error: ‘CompressedRangeData’ in namespace ‘cartographer::sensor::proto’ does not name a type
 proto::CompressedRangeData ToProto(
 ^
../cartographer/sensor/range_data.h:54:37: error: ‘CompressedRangeData’ in namespace ‘cartographer::sensor::proto’ does not name a type
 CompressedRangeData FromProto(const proto::CompressedRangeData& proto);
                                     ^
../cartographer/sensor/range_data.h:54:65: error: ISO C++ forbids declaration of ‘proto’ with no type [-fpermissive]
 CompressedRangeData FromProto(const proto::CompressedRangeData& proto);
                                                                 ^
[47/237] Building CXX object CMakeFiles/cartographer.dir/cartographer/sensor/range_data.cc.o
FAILED: /usr/bin/c++    -O3 -DNDEBUG -isystem /usr/local/include/eigen3 -isystem /home/vecna/catkin_ws_cartographer/install_isolated/include -isystem /usr/local/include -isystem /usr/include/cairo -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/freetype2 -isystem /usr/include/libpng12 -I. -I.. -isystem /usr/src/gmock/gtest/include     -pthread -std=c++11  -Wall -Wpedantic -Werror=format-security -Werror=missing-braces -Werror=reorder -Werror=return-type -Werror=switch -Werror=uninitialized -O3 -DNDEBUG -MMD -MT CMakeFiles/cartographer.dir/cartographer/sensor/range_data.cc.o -MF "CMakeFiles/cartographer.dir/cartographer/sensor/range_data.cc.o.d" -o CMakeFiles/cartographer.dir/cartographer/sensor/range_data.cc.o -c ../cartographer/sensor/range_data.cc
In file included from ../cartographer/sensor/range_data.cc:17:0:
../cartographer/sensor/range_data.h:52:1: error: ‘CompressedRangeData’ in namespace ‘cartographer::sensor::proto’ does not name a type
 proto::CompressedRangeData ToProto(
 ^
../cartographer/sensor/range_data.h:54:37: error: ‘CompressedRangeData’ in namespace ‘cartographer::sensor::proto’ does not name a type
 CompressedRangeData FromProto(const proto::CompressedRangeData& proto);
                                     ^
../cartographer/sensor/range_data.h:54:65: error: ISO C++ forbids declaration of ‘proto’ with no type [-fpermissive]
 CompressedRangeData FromProto(const proto::CompressedRangeData& proto);
                                                                 ^
../cartographer/sensor/range_data.cc:40:1: error: ‘CompressedRangeData’ in namespace ‘cartographer::sensor::proto’ does not name a type
 proto::CompressedRangeData ToProto(
 ^
../cartographer/sensor/range_data.cc:49:37: error: ‘CompressedRangeData’ in namespace ‘cartographer::sensor::proto’ does not name a type
 CompressedRangeData FromProto(const proto::CompressedRangeData& proto) {
                                     ^
../cartographer/sensor/range_data.cc:49:65: error: ISO C++ forbids declaration of ‘proto’ with no type [-fpermissive]
 CompressedRangeData FromProto(const proto::CompressedRangeData& proto) {
                                                                 ^
../cartographer/sensor/range_data.cc: In function ‘cartographer::sensor::CompressedRangeData cartographer::sensor::FromProto(const int&)’:
../cartographer/sensor/range_data.cc:51:32: error: request for member ‘origin’ in ‘proto’, which is of non-class type ‘const int’
       transform::ToEigen(proto.origin()), CompressedPointCloud(proto.returns()),
                                ^
../cartographer/sensor/range_data.cc:51:70: error: request for member ‘returns’ in ‘proto’, which is of non-class type ‘const int’
       transform::ToEigen(proto.origin()), CompressedPointCloud(proto.returns()),
                                                                      ^
../cartographer/sensor/range_data.cc:52:34: error: request for member ‘misses’ in ‘proto’, which is of non-class type ‘const int’
       CompressedPointCloud(proto.misses()),
                                  ^
../cartographer/sensor/range_data.cc:54:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1plus: some warnings being treated as errors
[47/237] Building CXX object CMakeFiles/cartographer.dir/cartographer/mapping_2d/scan_matching/fast_correlative_scan_matcher.cc.o
FAILED: /usr/bin/c++    -O3 -DNDEBUG -isystem /usr/local/include/eigen3 -isystem /home/vecna/catkin_ws_cartographer/install_isolated/include -isystem /usr/local/include -isystem /usr/include/cairo -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/freetype2 -isystem /usr/include/libpng12 -I. -I.. -isystem /usr/src/gmock/gtest/include     -pthread -std=c++11  -Wall -Wpedantic -Werror=format-security -Werror=missing-braces -Werror=reorder -Werror=return-type -Werror=switch -Werror=uninitialized -O3 -DNDEBUG -MMD -MT CMakeFiles/cartographer.dir/cartographer/mapping_2d/scan_matching/fast_correlative_scan_matcher.cc.o -MF "CMakeFiles/cartographer.dir/cartographer/mapping_2d/scan_matching/fast_correlative_scan_matcher.cc.o.d" -o CMakeFiles/cartographer.dir/cartographer/mapping_2d/scan_matching/fast_correlative_scan_matcher.cc.o -c ../cartographer/mapping_2d/scan_matching/fast_correlative_scan_matcher.cc
In file included from ../cartographer/mapping/trajectory_node.h:25:0,
                 from ../cartographer/mapping_2d/map_limits.h:26,
                 from ../cartographer/mapping_2d/probability_grid.h:31,
                 from ../cartographer/mapping_2d/scan_matching/fast_correlative_scan_matcher.h:33,
                 from ../cartographer/mapping_2d/scan_matching/fast_correlative_scan_matcher.cc:17:
../cartographer/sensor/range_data.h:52:1: error: ‘CompressedRangeData’ in namespace ‘cartographer::sensor::proto’ does not name a type
 proto::CompressedRangeData ToProto(
 ^
../cartographer/sensor/range_data.h:54:37: error: ‘CompressedRangeData’ in namespace ‘cartographer::sensor::proto’ does not name a type
 CompressedRangeData FromProto(const proto::CompressedRangeData& proto);
                                     ^
../cartographer/sensor/range_data.h:54:65: error: ISO C++ forbids declaration of ‘proto’ with no type [-fpermissive]
 CompressedRangeData FromProto(const proto::CompressedRangeData& proto);
                                                                 ^
[47/237] Building CXX object CMakeFiles/cartographer.dir/cartographer/sensor/ordered_multi_queue.cc.o
FAILED: /usr/bin/c++    -O3 -DNDEBUG -isystem /usr/local/include/eigen3 -isystem /home/vecna/catkin_ws_cartographer/install_isolated/include -isystem /usr/local/include -isystem /usr/include/cairo -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/freetype2 -isystem /usr/include/libpng12 -I. -I.. -isystem /usr/src/gmock/gtest/include     -pthread -std=c++11  -Wall -Wpedantic -Werror=format-security -Werror=missing-braces -Werror=reorder -Werror=return-type -Werror=switch -Werror=uninitialized -O3 -DNDEBUG -MMD -MT CMakeFiles/cartographer.dir/cartographer/sensor/ordered_multi_queue.cc.o -MF "CMakeFiles/cartographer.dir/cartographer/sensor/ordered_multi_queue.cc.o.d" -o CMakeFiles/cartographer.dir/cartographer/sensor/ordered_multi_queue.cc.o -c ../cartographer/sensor/ordered_multi_queue.cc
In file included from ../cartographer/sensor/data.h:22:0,
                 from ../cartographer/sensor/ordered_multi_queue.h:29,
                 from ../cartographer/sensor/ordered_multi_queue.cc:17:
../cartographer/sensor/range_data.h:52:1: error: ‘CompressedRangeData’ in namespace ‘cartographer::sensor::proto’ does not name a type
 proto::CompressedRangeData ToProto(
 ^
../cartographer/sensor/range_data.h:54:37: error: ‘CompressedRangeData’ in namespace ‘cartographer::sensor::proto’ does not name a type
 CompressedRangeData FromProto(const proto::CompressedRangeData& proto);
                                     ^
../cartographer/sensor/range_data.h:54:65: error: ISO C++ forbids declaration of ‘proto’ with no type [-fpermissive]
 CompressedRangeData FromProto(const proto::CompressedRangeData& proto);
                                                                 ^
[47/237] Building CXX object CMakeFiles/cartographer.dir/cartographer/sensor/compressed_point_cloud.cc.o
ninja: build stopped: subcommand failed.

**Comment by SirVer** [comment]
Did you `git pull` cartographer and cartographer_ros? It should build then again.
