### ISSUE TITLE
Submap updating and maintenance

### ISSUE THREAD

**Issue by johnzjq** [googlecartographer/cartographer#464]
Hi creators,
I am working on a simple implementation of lifelong mapping. I planned to firstly maintain the spatially overlapped submaps based on their timestamps and to trim the outdated ones, and secondly to insert newly incorporated range data based on the optimized trajectory to the FINISHED submaps for updating.
I would like to know your preferences or future plan for this.

**Comment by johnzjq** [comment]
Two problems remain: 1 triming arbitary submap 2 remove old range_data.

**Comment by damonkohler** [comment]
@johnzjq, could you give us some context for why you closed this? Is there a PR we should look at?

**Comment by johnzjq** [comment]
Hi @damonkohler There is none, thanks for your concern=) Initially I opened this issue but gradually found related discussions in some other issues, ie. trimming submap in the middle etc. Therefore I closed this issue for preventing any confusion.
