### ISSUE TITLE
decreased map quality after angular velocity estimation(#458)

### ISSUE THREAD

**Issue by jihoonl** [googlecartographer/cartographer#467]
After merging #458, our map quality significantly decreased even with a large search window of `real_time_correlative_scan_matcher`. It seems like #458 made cartographer relies more on odometry and made harder to use robots with imprecise odometry.
*Before*
![before2](https://user-images.githubusercontent.com/1556736/29562271-e39c415e-8738-11e7-9f96-bc6d403e6293.png)

*After*
![after2](https://user-images.githubusercontent.com/1556736/29562277-ea23478e-8738-11e7-9c4a-ee29b9aa7c3b.png)

I will send you an e-mail to explain how to reproduce it on your side.

**Comment by ojura** [comment]
Have you tried readjusting the occupied space, translation and rotation weights in Ceres scan matcher options?

**Comment by jihoonl** [comment]
It doesn't seem to help to obtain the same quality map as before.

**Comment by wohe** [comment]
How did you determine that #458 is the cause? I'm asking because #456 was merged soon afterwards and also makes use of odometry information. Did you check with #458 but without #456?

**Comment by jihoonl** [comment]
Yeah. I double checked that #458 is the cause. It was still breaking without #456.

**Comment by BrannonKing** [comment]
Can you retest this with the odometry fixes from last night?

**Comment by ojura** [comment]
#533 restored 2D w/ odometry to be pre-#499. This started occuring for @jihoonl even earlier, at #458, so I doubt #533 will help. But it doesn't hurt to try :)

**Comment by BrannonKing** [comment]
For the test image above, does that include IMU data or is it only Odometry + LaserScan?

**Comment by BrannonKing** [comment]
See my recent comment on the odometric rotation issues here: https://github.com/googlecartographer/cartographer/issues/534

**Comment by jihoonl** [comment]
![aa](https://user-images.githubusercontent.com/1556736/30862239-a4b12ada-a2cd-11e7-8c64-6b664d4f9460.png)

@BrannonKing Yes, it looks like the latest version mitigated the problem. The quality isn't as good as before though. And it is only odometry + LaserScan.

**Comment by SirVer** [comment]
I am closing this as it seems to be mostly a tuning issue after changes to the code. Without data and configuration, this is not actionable.
