### ISSUE TITLE
Rigid2/3d parameterless constructor is wrong

### ISSUE THREAD

**Issue by BrannonKing** [googlecartographer/cartographer#490]
The Rigid3d and Rigid2d parameterless constructors initialize their x position to 1. That's unexpected behavior. They should be using `translation_(Vector::Zero())` rather than identity. It was affecting me in my custom message handling; it may not be affecting anyone else. It could be related to odometry handlers' accuracy, but I couldn't prove that.

**Comment by macmason** [comment]
Try #491 ?

**Comment by wohe** [comment]
This was clearly a bug. Thanks a lot for finding and fixing it.
