### ISSUE TITLE
how to save a correct map in cartographer ??

### ISSUE THREAD

**Issue by yinnxinn** [googlecartographer/cartographer#520]
when i run the demo_revo_lds.launch using official data . everything's OK . 

         I save the map use "**rosrun map_server map_saver -f map**" ...got the map without occ  ... ..as follows : 
![1](https://user-images.githubusercontent.com/23116748/30322230-53b1a638-97eb-11e7-8160-212168c2bde2.png)

         and when i use the "**rosservice call /finishTrajectory "stem:'map'** " saved the map . I got the error as follows :+1: 
     **# ERROR: Unable to load type [cartographer_ros_msgs/WriteState].
     Have you typed 'make' in [cartographer_ros_msgs]?**

   it's the version problem resulted in this problem ?????
   shoud I rewrite the map_server source code to save an available map ????
   
   i would appreciate your answers .. thanks ~~

**Comment by ojura** [comment]
There is another issue about this, see
https://github.com/googlecartographer/cartographer_ros/issues/475#issuecomment-321261237

To summarize: either patch your map_saver as described in the link above, or use the assets writer.

**Comment by cschuet** [comment]
Closing. Thanks @ojura.
