### ISSUE TITLE
Utilize RangeData::misses information in 3D mapping

### ISSUE THREAD

**Issue by Dumbear** [googlecartographer/cartographer#539]
Hi, according to the definition, `misses` in `RangeData` are points in the direction of rays for which no return was detected.
I noticed that in 2D mapping, these rays are used to make the probability grid, see code here: https://github.com/googlecartographer/cartographer/blob/0cbc420b0267aaf4841c77c127165d32e37789f0/cartographer/mapping_2d/ray_casting.cc#L199-L203
But in 3D mapping, there is no use of these rays. `RangeDataInserter` only considers `returns` but no `misses`. See here: https://github.com/googlecartographer/cartographer/blob/0cbc420b0267aaf4841c77c127165d32e37789f0/cartographer/mapping_3d/range_data_inserter.cc#L79-L93
But actually the paths along the no-returned rays are also free space. So could it be reasonable to also call `InsertMissesIntoGrid` for `range_data.misses`?
Thanks.

**Comment by damonkohler** [comment]
These are ignored in 3D for performance reasons. When inserting hits in 3D, only some of the traversed free space is inserted before the hit. Given that behavior, it's a bit difficult to imagine a reasonable, similar behavior for misses.
