### ISSUE TITLE
Better support for RGB-D data

### ISSUE THREAD

**Issue by cschuet** [googlecartographer/cartographer#545]
RGB-D data provides colored point clouds that can be input into Cartographer for scan matching (which would currently ignore  the color information). However the results are quite bad. The current theory is that the noise model of RGB-D cameras is different from that of laser scanners (the depth uncertainty in RGB-D increases steeply with depth, less so for laser scanners).

We should invest more thought into this and find a way to reliably scan match against RGB-D data.

**Comment by SirVer** [comment]
Related and possible interesting for tuning: googlecartographer/cartographer_ros#318

**Comment by Changliu52** [comment]
I understand the color will be ignored in scan matching, but for a successful rgbd mapping, will the color information remain in the map with the asset_writer?

**Comment by SirVer** [comment]
@Changliu52 If it is in the bag, it will also be used in the asset writer.

**Comment by Changliu52** [comment]
Perfect! Great. Thank you very much.

Chang

**Comment by cschuet** [comment]
Duplicate of #33
