### ISSUE TITLE
Trim all submaps when trajectory finishes if pure localization = true

### ISSUE THREAD

**Issue by jihoonl** [googlecartographer/cartographer#560]
If a trajectory is in a pure localization mode, it should remove all submaps when it finishes.

**Comment by wohe** [comment]
I think I'm missing context here. Can you elaborate a bit on what you are trying to achieve? I also do not understand the rationale behind #562.

**Comment by jihoonl** [comment]
Assume that you loaded a frozen trajectory and started a pure localization enabled trajectory. Then, robot moved around for a while and the trajectory is finished by calling /finish_trajectory service. The last 3 submaps generated by the pure localization trajectory will remain in the sparse pose graph, and they will be optimized and serialized into pbstream file. 

Since it is _"pure localization"_, I think it should remove trajectory related data when it is finished. Otherwise, the sparse pose graph and pbstream file would get dirtier everytime pure localization trajectory is started and finished.
