### ISSUE TITLE
Trim odometry data from optimization_problem

### ISSUE THREAD

**Issue by jihoonl** [googlecartographer/cartographer#594]
TrimTrajectoryNode [2d](https://github.com/googlecartographer/cartographer/blob/master/cartographer/mapping_2d/sparse_pose_graph/optimization_problem.cc#L89), [3d](https://github.com/googlecartographer/cartographer/blob/master/cartographer/mapping_3d/sparse_pose_graph/optimization_problem.cc#L92) in optimization problem should also trim obsolte odometry data.

**Comment by wohe** [comment]
We added some projects to better communicate our short term roadmap. See https://github.com/googlecartographer/cartographer/projects/1. Our intention is to address trimming arbitrary parts of the odometry data.

**Comment by wohe** [comment]
Fixed by #655.
