### ISSUE TITLE
Add time component to points in PointCloud.

### ISSUE THREAD

**Issue by gaschler** [googlecartographer/cartographer#600]
Points are not scanned at the same time, but continuously.
In order to improve local quality, we would like to build the local trajectory from timed points.
This requires that PointCloud (and RangeData) store the relative timing of points.
Let's make PointCloud store points as Vector4f and put the relative time in the fourth component.

**Comment by ojura** [comment]
Isn't this the same thing as #573?

**Comment by SirVer** [comment]
Yup.
