### ISSUE TITLE
Remove using std::string and switch to using std::string directly everywhere.

### ISSUE THREAD

**Issue by catskul** [googlecartographer/cartographer#622]
https://github.com/googlecartographer/cartographer/blob/e10650910e157bd68c55f4d1bc6603f25f89d293/cartographer/common/port.h#L37

Should probably not be in the header file, or at least should be within one of the owned namespaces.

Fixing may cause knock on build failures for any include graph descendant.

**Comment by SirVer** [comment]
Actually that is required, unfortunately. The reason is that inside google, `string` is reimplemented as more efficient solution for our most common use cases, so `std::string` != `string`. It is API compatible though. Since Cartographer has to work in google and outside, we have to use `string` everywhere to be compatible and for the external code, we require this using.

The [abseil](https://github.com/abseil/abseil-cpp) effort is working towards fixing this, so we will be able to soon remove this, but unfortunately not as of right now.

**Comment by ojura** [comment]
@SirVer, what exactly is 'google'? :-)

**Comment by SirVer** [comment]
@ojura Most of google's source code is stored in [one big repository called Piper](https://cacm.acm.org/magazines/2016/7/204032-why-google-stores-billions-of-lines-of-code-in-a-single-repository/fulltext), this includes compiler, c++ std library and most of googles code. We use [Bazel](https://www.bazel.build/) to build everything from scratch - so, if you write a hello world, we start by compiling the c++ standard library (including our own changes) and end with compiling your source. All dependencies are build from source as well - which is all checked into Piper.

This allows us to make changes like the one I referred to above - but it also means that you require a datacenter to build hello world, more or less.

**Comment by catskul** [comment]
@SirVer interesting. 

Would it be possible to move the `using` inside of  the cartographer namespace so that at least it's not in the global namespace? Or is being in the global namespace part of how this string switcheroo trick works?

**Comment by SirVer** [comment]
Yes, unfortunately that is the trick. I am investigating if it is feasible to switch to std::string for Cartographer and remove this workaround. It will cost some performance internally, but maybe it doesn't matter as much for Cartographer.

**Comment by SirVer** [comment]
> start by compiling the c++ standard library

I was corrected by a colleague that this is not true. We prebuild the standard library, but still build all dependencies of your code.

**Comment by catskul** [comment]
Sure.

I'll try to create a patch for this if I can find some time this week

**Comment by ojura** [comment]
One other option would be to expose a configurable option through CMake (`CARTOGRAPHER_USE_STD_STRING`?), and in `port.h` wrap the global `using std::string` inside an `#ifdef` which depends on this option.

**Comment by catskul** [comment]
Here's one version of a fix, that just moves the typedefs into the cartographer namespace: 

https://github.com/googlecartographer/cartographer/pull/637

I'll add another pull request for the more complete alternative later this week which changes references of string to std::string in the code base.
