### ISSUE TITLE
Typo in correlative scan matching

### ISSUE THREAD

**Issue by TrophyBuck** [googlecartographer/cartographer#634]
I'm pretty sure this is a typo - been looking through scan matching, and line 81 & 82 in correlative_scan_matcher.h seem switched.  X is made from the y offset and Y is made from the x offset.

File here: https://github.com/googlecartographer/cartographer/blob/master/cartographer/mapping_2d/scan_matching/correlative_scan_matcher.h

**Comment by wohe** [comment]
This might look confusing, but I believe it is correct.
- when showing a map as an image (e.g. a PNG) the handedness of the pixel coordinate system (x to the right, y down) is different from the metric coordinate system (as in ROS, e.g. seen from above x up, y left), so it must change at some point between the metric coordinates and visualization
- we do the switch when going from meters to pixels (e.g. the place you point at)
- it might be less confusing (similar to what we do in 3D) to only do this change at the very end when visualizing the pixel grid, but this is a lot of work and only a small code improvement, thus not important right now
