### ISSUE TITLE
2D pure localization slow on same map.

### ISSUE THREAD

**Issue by gaschler** [googlecartographer/cartographer#647]
As reported by @gladxu in https://github.com/googlecartographer/cartographer_ros/issues/557, 2D pure localization fails on exactly the same map.

```
roslaunch cartographer_ros offline_backpack_2d.launch bag_filenames:=${HOME}/Downloads/cartographer_paper_deutsches_museum.bag

roslaunch cartographer_ros demo_backpack_2d_localization.launch bag_filename:=${HOME}/Downloads/cartographer_paper_deutsches_museum.bag map_filename:=${HOME}/Downloads/cartographer_paper_deutsches_museum.bag.pbstream
```

![screenshot from 2017-10-26 16 01 09](https://user-images.githubusercontent.com/18653443/32043175-8f2491aa-ba6c-11e7-8d15-2ebac4b81631.png)

In rviz, one can see that good constraints are found, but they are long delayed, the work queue is too long. Therefore, the currently reported localization is way off due to the drift in between.

**Comment by gaschler** [comment]
In this case, the constraint builder spends more time on scan matching, so work queues up.
Localization on exactly the same map is a special case with a large number of matches.

One way to tune this would be sample fewer potential constraints in general for localization.
I will do more evaluation, but localization has more work with MaybeAddGlobalConstraint than usual SLAM so maybe the default value could be lower
```
SPARSE_POSE_GRAPH.global_sampling_ratio =
    0.2 * SPARSE_POSE_GRAPH.global_sampling_ratio
```

This scenario can be solved with tuning as follows,
```
SPARSE_POSE_GRAPH.global_sampling_ratio = 0.001
SPARSE_POSE_GRAPH.constraint_builder.sampling_ratio = 0.1
```

so closing the issue.

**Comment by ojura** [comment]
Might be useful to add this to the tuning guide.

**Comment by ojura** [comment]
@cshuet ping :-)

**Comment by ojura** [comment]
@cshuet ping :-) do you agree?

**Comment by cschuet** [comment]
Agreed. @gaschler will update the guide.

**Comment by gaschler** [comment]
I'm updating the tuning guide with https://github.com/googlecartographer/cartographer_ros/pull/653

**Comment by sockhands** [comment]
Is there any way to establish an upper bound to the number of constraints within the same map? It seems that as a robot repeatedly retraces the same path through an established map, it continues to find and add more and more constraints. This corresponds to a gradual increase in CPU load over time, which eventually becomes untenable.

I have tuned various parameters, decreased sampling_ratio, increased the min_score for adding constraints etc. This has helped to slow the increase, but given enough time the constraints inevitably pile up. Does cartographer ever prune/cull older constraints?

**Comment by gaschler** [comment]
@sockhands In pure localization mode, constraints of older submaps are pruned (assuming that global SLAM keeps up), even when pruning removes your last constraint to the frozen map. In mapping, constraints will always be added as you expected, but we have successfully run very large problems.

(This question could have been a new issue since is not directly related to this issue.)

**Comment by sockhands** [comment]
Thanks @gaschler, I managed to work things out not too long after my comment yesterday. I was confused because the count for added constraints reported by the cartographer log seems to be an ongoing total, and doesn’t drop when an older submap is pruned.
