### ISSUE TITLE
New release of cartographer?

### ISSUE THREAD

**Issue by damienrg** [googlecartographer/cartographer#695]
This question is asked a bit late (as proto3 switch is already made) but as cloud mapping slam introduces a bunch of changes, is it not the time to create a new release of cartographer?

**Comment by cschuet** [comment]
I think that's a good idea. I wanted to think about having more regular releases anyways - hopefully with cool code names ;) We can cut right before the proto3 change, i.e. ed71914805b8a51f4b7b01abb40656a5f41a4f44.

**Comment by cschuet** [comment]
Ok, I see package.xml is usually modified with the release. So maybe we can't do this retroactively.

**Comment by cschuet** [comment]
Release is on its way. Closing.
