### ISSUE TITLE
Misc: CMake warning

### ISSUE THREAD

**Issue by ojura** [googlecartographer/cartographer#727]
@cschuet In 
https://github.com/googlecartographer/cartographer/blob/ee9c61a7369e3a4f24bbbb72745e37c690f28587/CMakeLists.txt#L62-L72

the following CMake warnings are triggered:
```
CMake Warning at cartographer/cmake/functions.cmake:139 (message):
  Unnecessary use of list_remove_item.  Consider using list(REMOVE_ITEM
  ALL_SRCS ${ALL_GRPC_FILES}.
```

**Comment by gaschler** [comment]
Thanks. #739 cleans this up and also fixes which headers are installed.
