### ISSUE TITLE
Support non-Ubuntu-package version of gmock and gtest

### ISSUE THREAD

**Issue by at-wat** [googlecartographer/cartographer#73]
cmake/functions.cmake depends on Ubuntu package version of gmock and gtest install.
```
macro(google_enable_testing)
  set(GMOCK_SRC_DIR "/usr/src/gmock" CACHE STRING "Path to google-mock sources.")
  add_subdirectory(${GMOCK_SRC_DIR} "${CMAKE_CURRENT_BINARY_DIR}/gmock")
```
For example in Fedora 24, /usr/src/gmock does not contains CMakeLists.txt.

Latest (1.8+) version of googletest (containing gmock) supports system wide install again.
So, add_subdirectory for gmock will be no longer required in latest gtest environment.
(I have just commented out these lines for my build.)

Also, in environments with a built-from-source version of gmock, libgmock_main requires linking pthread.
I have simply modified macro(_common_test_stuff) as following:
```
diff --git a/cmake/functions.cmake b/cmake/functions.cmake
index 27f0beb..031412e 100644
--- a/cmake/functions.cmake
+++ b/cmake/functions.cmake
@@ -221,7 +221,7 @@ macro(_common_test_stuff)
   # Make sure that gmock always includes the correct gtest/gtest.h.
   target_include_directories("${NAME}" SYSTEM PRIVATE
     "${GMOCK_SRC_DIR}/gtest/include")
-  target_link_libraries("${NAME}" gmock_main)
+  target_link_libraries("${NAME}" gmock_main pthread)
 endmacro()
 
 function(google_catkin_test NAME)
```
(This hard-code should be replaced using find_package.)

Currently, I could not make a PR about this since I have not understood the structure of Google-style CMake.

**Comment by lukehutch** [comment]
Using the system-wide version of gtest seems to cause linkage problems in Fedora too.

https://github.com/googlecartographer/cartographer/issues/1611

Seems to be a case of the following:

https://groups.google.com/forum/#!topic/googletestframework/Zo7_HOv1MJ0

Probably Cartographer should clone and build its own snapshots of these libraries, as recommended in the above thread.
