### ISSUE TITLE
Run tests unders ASAN in the testing pipeline

### ISSUE THREAD

**Issue by SirVer** [googlecartographer/cartographer#746]
Recently, in one of my other open source projects a contributor enabled optional ASAN linking. It was very useful to track down a lot of bugs and it is now very simple to do with GCC and clang.

ASAN has costs, so we should not enable it by default. But it should run in the testing pipeline.

[Here is the Widelands commit](http://bazaar.launchpad.net/~widelands-dev/widelands/trunk/revision/8498) enabling it.

**Comment by gaschler** [comment]
For documentation, we have a script merged in #745 that ASAN-checks the tests, built by clang.

**Comment by cschuet** [comment]
Currently we have no plans to add this to Travis. Closing until that changes.
