### ISSUE TITLE
How to set up the environment variables of two spaces

### ISSUE THREAD

**Issue by ytgcljj** [googlecartographer/cartographer#812]
I have two workspaces, onecartographer, one velodyne, cartographer is compiled by catkin_make_iso, velodyn is compiled by catkin_make, now the question is how to set up two environment variables, can I use an environment variable?
 thanks

**Comment by SirVer** [comment]
You can't, but you can just `mv first_space/src/* second_space/src` and only have one space.

this is also not related to Cartographer. Should the above suggestion not work for you, please try https://answers.ros.org/questions/.

**Comment by ytgcljj** [comment]
I am under a SRC, but these are two variables, one is under devel, one is under install_isolated, I cannot install cartographer, no other space can be installed.

**Comment by SirVer** [comment]
just move the velodyne one to the cartographer workspace and build both with `catkin_make_isolated`. I did that before, it works.

**Comment by ytgcljj** [comment]
thanks
