### ISSUE TITLE
How to add new parameters in lua

### ISSUE THREAD

**Issue by anjiss** [googlecartographer/cartographer#815]
I want to add a new parameter in lua file, eg "trajectory_builder_3d.lua", like min_range and max_range, I'm going to add a parameter named max_height:

TRAJECTORY_BUILDER_3D = {
  min_range = 1.,
  max_range = MAX_3D_RANGE,
  max_height = 3,
  num_accumulated_range_data = 1,
  voxel_filter_size = 0.15,
  ...
}

I've done some corresponding change in "local_trajectory_builder_options.proto":

// NEXT ID: 19
message LocalTrajectoryBuilderOptions {
  // Rangefinder points outside these ranges will be dropped.
  float min_range = 1;
  float max_range = 2;
  float max_height = 18;
  ...
}

However, it's seems I still miss something and I get error as below:

[FATAL] [1515754171.480793177]: F0112 18:49:31.000000 26660 lua_parameter_dictionary.cc:411] Check failed: 1 == reference_counts_.count(key) (1 vs. 0) Key 'max_height' was used the wrong number of times. reference_counts_.count(key)0

So the problem is what should I do next? it's kinda dummy question, but help me figure it out, plz!

**Comment by gaschler** [comment]
I'm not aware of a commit that exactly adds one config parameter, but you could look at https://github.com/googlecartographer/cartographer/pull/503 which moves a parameter to a different files and does more.

For a patch-related question, it would be better if you link to a commit or pull request in your repo, which was created by forking master, so we can see exactly your patch.

Closing as answered, feel free to re-open.
