### ISSUE TITLE
Ceres optimization: casting scalars to Jets should be avoided when possible

### ISSUE THREAD

**Issue by ojura** [googlecartographer/cartographer#900]
I stumbled upon [this](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/9241/6) and [this](https://groups.google.com/d/msg/ceres-solver/7ZH21XX6HWU/Z3E-k2fbAwAJ) (doesn't seem to apply for quaternions, though - I posted a question over there about this).

Perhaps if we got rid of these in Cartographer, we would get a small speedup. E.g. replacing things like `T(2.0)` with `2.0`.

**Comment by pifon2a** [comment]
Solved by https://github.com/googlecartographer/cartographer/pull/998.
