### ISSUE TITLE
Can not build map 

### ISSUE THREAD

**Issue by xiangkui123** [googlecartographer/cartographer#943]
hello everyone!
      Test 3D drawing, but can not be a normal map,No matter how to move the backpack, the built map is rotated at the origin!

**Comment by cschuet** [comment]
Hi, your report is a little vague. Can you tell us more about your setup, a screen shot or capture maybe of the problem. Configuration files and a recorded bag would also help of course.

**Comment by xiangkui123** [comment]
![screenshot from 2018-02-28 16 53 17](https://user-images.githubusercontent.com/9855744/36778617-3880f232-1ca8-11e8-9074-34b4a7b2f3d9.png)
I used velodyne 16 and stim300.

**Comment by cschuet** [comment]
First suspicion is that your IMU to rangefinder transform is not correctly specified in your urdf. Can you check that?

**Comment by xiangkui123** [comment]
I modified urdf file, What calibration tools are not used, just a simple measurement of translation vector, imu and radar coordinate system is roughly the same．What calibration tools are you using?（：
