### ISSUE TITLE
Test 3D mapping, but the effect is not good

### ISSUE THREAD

**Issue by xiangkui123** [googlecartographer/cartographer#956]
![screenshot from 2018-03-05 14 51 26](https://user-images.githubusercontent.com/9855744/36961584-0fe1a686-2087-11e8-8947-4045875fa0b7.png)
![screenshot from 2018-03-05 14 46 02](https://user-images.githubusercontent.com/9855744/36961585-100a82fe-2087-11e8-8a51-4912c8cd5565.png)
I use velodyne32 and fsas imu

**Comment by gaschler** [comment]
From the screenshots alone, it's hard to answer anything.

For a configuration or tuning issue, please give more details following the issue template https://raw.githubusercontent.com/googlecartographer/cartographer_ros/master/.github/ISSUE_TEMPLATE

**Comment by xiangkui123** [comment]
Thank you, the problem has been solved！
