### ISSUE TITLE
Without libsuitesparse-dev, performance degrades severely without warning

### ISSUE THREAD

**Issue by gaschler** [googlecartographer/cartographer#971]
When `libsuitesparse-dev` is not installed, (Ceres) optimization will take >100 times longer.
It would nice to warn about this.

**Comment by ojura** [comment]
Ah, I remember running into this a year ago. That was my first PR:
https://github.com/googlecartographer/cartographer/pull/189

Ceres declares a `SparseLinearAlgebraLibrary` CMake component when it's built against `SuiteSparse`, `CXSparse` or `EigenSparse` (see [here](https://ceres-solver.googlesource.com/ceres-solver/+/master/cmake/CeresCompileOptionsToComponents.cmake#73)). Seems like not using `SuiteSparse` results in slow optimization? Then we can change that line to require `SuiteSparse` exactly.
