### ISSUE TITLE
about visualization

### ISSUE THREAD

**Issue by deepmeng** [googlecartographer/cartographer#978]
hello, I'm curious about how you load the triangle in rviz?
![image](https://user-images.githubusercontent.com/8176780/37249278-85c92134-251f-11e8-9c50-0a75389d3985.png)

**Comment by cschuet** [comment]
@SirVer Did you create the demo animation?

**Comment by ojura** [comment]
AFAIK that was a visualization tool which predates the rviz plugin, which was not publically released.

**Comment by SirVer** [comment]
@cschuet @damonkohler did. But @ojura is correct, this is our old Java based viz, predating cartographer_ros.

@deepmeng We drew the cursor as a separate layer in our Viz tool using a hardcoded set of points, transformed according to the current pose.

**Comment by deepmeng** [comment]
Interesting! Thanks for your replies.

**Comment by ojura** [comment]
@deepmeng you can specify simple shapes in an urdf and display them in rviz (e.g. see the `<geometry>` tag). You can also specify in the urdf a model (in the collada format, IIRC) and attach it to a link - in this case, `base_link`.
