### ISSUE TITLE
Reuse code from absl lib.

### ISSUE THREAD

**Issue by pifon2a** [googlecartographer/cartographer#984]
Some parts of cartographer can be removed and replaced with analogs from absl lib.
`mutex` and `optional` will be removed first.

**Comment by SirVer** [comment]
Alex, can you outline the plan to depend on absl? How does this tie into cmake and bazel?

I am very excited about getting absl's mutex.

**Comment by pifon2a** [comment]
I want to have support for absl in both cmake and bazel modes. With CMake it is gonna be a bit tricky.

**Comment by gaschler** [comment]
See #1138 for an evaluation of `absl::Mutex`.
